## Static
- type: latheRecipePack
  id: SecurityEquipmentStaticPirate
  recipes:
  - ClothingOuterArmorDuraVestK9

- type: latheRecipePack
  id: SecurityAmmoStaticPirate
  recipes:
  - MagazineUniversalMagnumEmpty
  - MagazineUniversalMagnum
  - MagazineUniversalMagnumRubber
  - MagazineMagnumEmpty
  - MagazineMagnum
  # 9.5mm
  - MagazineCaselessRifleEmpty
  - MagazineCaselessRifleStandard
  - MagazineBoxCaselessRifleStandard

## Dynamic
- type: latheRecipePack
  id: SecurityHardsuitsPirate
  recipes:
  - ClothingOuterHardsuitCombatK9
  - ClothingOuterHardsuitCombatRiotK9

- type: latheRecipePack
  id: SecurityAmmoPirate
  recipes:
  # 45. Mk 32
  - MagazineUniversalMagnumUranium
  - MagazineUniversalMagnumIncendiary
  - MagazineMagnumUranium

- type: latheRecipePack
  id: SecurityUtilityPirate
  recipes:
  - EnergyDomeTurtle
