// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Pirate.Voting.UI;
using Content.Client.Stylesheets;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VotePopup : Control
    {
        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IVoteManager _voteManager = default!;
        [Dependency] private readonly IEntityNetworkManager _net = default!;

        private readonly VoteManager.ActiveVote _vote;
        private readonly PirateVoteOption[] _voteOptions; // Pirate - map vote previews
        private readonly NetEntity? _targetEntity;

        public VotePopup(VoteManager.ActiveVote vote)
        {
            _vote = vote;
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSystem;

            if (_vote.TargetEntity != null && _vote.TargetEntity != 0)
            {
                _targetEntity = new NetEntity(_vote.TargetEntity.Value);
                FollowVoteTarget.Visible = true;
                FollowVoteTarget.OnPressed += _ => AttemptFollowVoteEntity();
            }

            Modulate = Color.White.WithAlpha(0.75f);
            _voteOptions = new PirateVoteOption[vote.Entries.Length]; // Pirate - map vote previews
            var group = new ButtonGroup();

            for (var i = 0; i < _voteOptions.Length; i++)
            {
                var option = new PirateVoteOption();
                option.Button.ToggleMode = true;
                option.Button.Group = group;

                var entry = vote.Entries[i];
                if (entry.Icon is { } icon)
                {
                    option.Button.IconLeft.TexturePath = icon;
                    option.Button.IconRight.TexturePath = icon;
                }
                else
                {
                    option.Button.IconLeft.Visible = false;
                    option.Button.IconRight.Visible = false;
                }

                if (entry.Preview is { } preview)
                    option.Preview.SetPrototype(preview);
                else
                    option.Preview.Visible = false;

                _voteOptions[i] = option;
                VoteOptionsContainer.AddChild(option);
                var i1 = i;
                option.Button.OnPressed += _ => _voteManager.SendCastVote(vote.Id, i1);
            }
        }

        public void UpdateData()
        {
            VoteTitle.SetMessage(FormattedMessage.FromUnformatted(_vote.Title));
            VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", _vote.Initiator));

            for (var i = 0; i < _voteOptions.Length; i++)
            {
                var entry = _vote.Entries[i];
                if (_vote.DisplayVotes)
                {
                    _voteOptions[i].Button.IconLabel.Text = Loc.GetString("ui-vote-button", ("text", entry.Text), ("votes", entry.Votes));
                }
                else
                {
                    _voteOptions[i].Button.IconLabel.Text = Loc.GetString("ui-vote-button-no-votes", ("text", entry.Text));
                }

                if (_vote.OurVote == i)
                    _voteOptions[i].Button.Pressed = true;
            }
        }

        private void AttemptFollowVoteEntity()
        {
            if (_targetEntity != null)
            {
                var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
                _net.SendSystemNetworkMessage(msg);
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            // Logger.Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

            var curTime = _gameTiming.RealTime;
            var timeLeft = _vote.EndTime - curTime;
            if (timeLeft < TimeSpan.Zero)
                timeLeft = TimeSpan.Zero;

            // Round up a second.
            timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

            TimeLeftBar.Value = Math.Min(1, (float) ((curTime.TotalSeconds - _vote.StartTime.TotalSeconds) /
                                                     (_vote.EndTime.TotalSeconds - _vote.StartTime.TotalSeconds)));

            TimeLeftText.Text = $"{timeLeft:m\\:ss}";
        }
    }
}
