using Content.Client._Funkystation.VendingMachines.UI;
using Content.Shared._Pirate.Banking;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Funkystation.Banking.UI;

public enum AtmKeypadPhase
{
    WaitingForCard,
    WaitingForAmount,
    WaitingForPin,
    ShowingResult,
}

[GenerateTypedNameReferences]
public sealed partial class AtmKeypadWindow : FancyWindow
{
    [Dependency] private IRobustRandom _random = null!;
    [Dependency] private IEntityManager _entManager = null!;
    private readonly SharedAudioSystem _audio;

    public event Action<ATMRequestWithdrawMessage>? OnWithdrawAttempt;
    public EntityUid AtmOwner;
    public EntityUid? User;

    private AtmKeypadPhase _phase = AtmKeypadPhase.WaitingForCard;
    private readonly List<int> _amountBuffer = new();
    private readonly List<int> _pinBuffer = new();
    private int _balance;
    private bool _hasCard;

    private float _blinkTimer;
    private float _inactivityTimer;
    private float _powerSagTimer;
    private bool _cursorVisible = true;
    private bool _showingResult;

    private readonly int[] _bluesScale = [0, 2, 3, 4, 5, 6, 7, 9, 10];

    private readonly Color _redOffColor = Color.FromHex("#440000");
    private readonly Color _redOnColor = Color.FromHex("#ff3333");
    private readonly Color _greenOffColor = Color.FromHex("#004400");
    private readonly Color _greenOnColor = Color.FromHex("#33ff33");

    public AtmKeypadWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = _entManager.System<SharedAudioSystem>();

        BuildNumpad();
        ResetLedIndicators();
        UpdateDisplay();
    }

    private void BuildNumpad()
    {
        NumpadGrid.RemoveAllChildren();

        for (var i = 1; i <= 9; i++)
        {
            var number = i;
            var shift = _bluesScale[number - 1];
            var pitch = MathF.Pow(2f, shift / 12f);

            var key = new VendingMachineKeypadKey(number.ToString());
            key.OnKeyPressed += () => OnNumberPressed(number, pitch);
            NumpadGrid.AddChild(key);
        }

        var clearKey = new VendingMachineKeypadKey(Loc.GetString("atm-keypad-clear"));
        clearKey.SetTint(Color.FromHex("#ffb3b3"), Color.FromHex("#ffcccc"), Color.FromHex("#800000"));
        clearKey.OnKeyPressed += () =>
        {
            _audio.PlayPredicted(new SoundPathSpecifier("/Audio/Machines/Nuke/general_beep.ogg"), AtmOwner, User, new AudioParams().WithVolume(-4f).WithPitchScale(0.7f));
            ClearBuffer();
        };
        NumpadGrid.AddChild(clearKey);

        var zeroKey = new VendingMachineKeypadKey("0");
        zeroKey.OnKeyPressed += () => OnNumberPressed(0, MathF.Pow(2f, 12f / 12f));
        NumpadGrid.AddChild(zeroKey);

        var enterKey = new VendingMachineKeypadKey(Loc.GetString("atm-keypad-enter"));
        enterKey.SetTint(Color.FromHex("#b3ffb3"), Color.FromHex("#ccffcc"), Color.FromHex("#004d00"));
        enterKey.OnKeyPressed += SubmitBuffer;
        NumpadGrid.AddChild(enterKey);
    }

    public void UpdateState(ATMBuiState state)
    {
        _balance = state.AccountBalance;
        _hasCard = state.HasCard;

        if (!_hasCard)
        {
            _phase = AtmKeypadPhase.WaitingForCard;
            _amountBuffer.Clear();
            _pinBuffer.Clear();
            _showingResult = false;
        }
        else if (_phase == AtmKeypadPhase.WaitingForCard)
        {
            _phase = AtmKeypadPhase.WaitingForAmount;
            _amountBuffer.Clear();
            _pinBuffer.Clear();
            _showingResult = false;
        }

        UpdateDisplay();
    }

    private void OnNumberPressed(int number, float pitch)
    {
        if (_showingResult || _phase == AtmKeypadPhase.WaitingForCard)
            return;

        _audio.PlayPredicted(new SoundPathSpecifier("/Audio/Machines/Nuke/general_beep.ogg"), AtmOwner, User, new AudioParams().WithVolume(-4f).WithPitchScale(pitch));

        _cursorVisible = true;
        _blinkTimer = 0f;
        _inactivityTimer = 0f;

        if (_phase == AtmKeypadPhase.WaitingForAmount)
            _amountBuffer.Add(number);
        else if (_phase == AtmKeypadPhase.WaitingForPin)
            _pinBuffer.Add(number);

        UpdateDisplay();
    }

    private void ClearBuffer()
    {
        if (_showingResult)
            return;

        _amountBuffer.Clear();
        _pinBuffer.Clear();
        _cursorVisible = true;
        _blinkTimer = 0f;
        _inactivityTimer = 0f;
        UpdateDisplay();
    }

    private void SubmitBuffer()
    {
        if (_showingResult || _phase == AtmKeypadPhase.WaitingForCard)
            return;

        if (_phase == AtmKeypadPhase.WaitingForAmount)
        {
            if (_amountBuffer.Count == 0)
            {
                ShowResult(Loc.GetString("atm-keypad-no-amount"), false, true);
                return;
            }

            _phase = AtmKeypadPhase.WaitingForPin;
            _pinBuffer.Clear();
            _cursorVisible = true;
            _blinkTimer = 0f;
            _inactivityTimer = 0f;
            UpdateDisplay();
            _audio.PlayPredicted(new SoundPathSpecifier("/Audio/Machines/Nuke/general_beep.ogg"), AtmOwner, User, new AudioParams().WithVolume(-4f).WithPitchScale(1.4f));
            return;
        }

        if (_phase == AtmKeypadPhase.WaitingForPin)
        {
            if (_pinBuffer.Count != 4)
            {
                ShowResult(Loc.GetString("atm-keypad-pin-4-digits"), false, true);
                return;
            }

            var amount = ParseBuffer(_amountBuffer);
            if (amount <= 0 || amount > _balance)
            {
                ShowResult(Loc.GetString("atm-keypad-no-funds"), false, true);
                return;
            }

            var pin = int.Parse(string.Concat(_pinBuffer));

            OnWithdrawAttempt?.Invoke(new ATMRequestWithdrawMessage(amount, pin));

            ShowResult(Loc.GetString("atm-keypad-processing"), true, false);
            _powerSagTimer = 0.15f;
        }
    }

    private void ShowResult(string text, bool success, bool playSound)
    {
        _showingResult = true;

        if (success)
        {
            BufferLabel.FontColorOverride = Color.Green;
            GreenLed.Modulate = _greenOnColor;
        }
        else
        {
            BufferLabel.FontColorOverride = Color.Red;
            RedLed.Modulate = _redOnColor;
        }

        BufferLabel.Text = text;

        if (playSound)
        {
            if (success)
            {
                _audio.PlayPredicted(new SoundPathSpecifier("/Audio/_Pirate/Machines/polaroid1.ogg"), AtmOwner, User, new AudioParams().WithVolume(-4f));
            }
            else
            {
                _audio.PlayPredicted(new SoundPathSpecifier("/Audio/_Pirate/Machines/buzz-sigh.ogg"), AtmOwner, User, new AudioParams().WithVolume(-4f));
            }
        }

        _amountBuffer.Clear();
        _pinBuffer.Clear();

        Timer.Spawn(TimeSpan.FromSeconds(1.5),
            () =>
            {
                if (Disposed)
                    return;

                _showingResult = false;
                _phase = _hasCard ? AtmKeypadPhase.WaitingForAmount : AtmKeypadPhase.WaitingForCard;
                ResetLedIndicators();
                BufferLabel.FontColorOverride = Color.FromHex("#33ff33");
                UpdateDisplay();
            });
    }

    private void ResetLedIndicators()
    {
        RedLed.Modulate = _redOffColor;
        GreenLed.Modulate = _greenOffColor;
    }

    private void UpdateDisplay()
    {
        switch (_phase)
        {
            case AtmKeypadPhase.WaitingForCard:
                StatusLabel.Text = Loc.GetString("atm-keypad-insert-card");
                BalanceLabel.Text = "";
                ModeLabel.Text = "";
                break;
            case AtmKeypadPhase.WaitingForAmount:
                StatusLabel.Text = Loc.GetString("atm-keypad-enter-amount");
                BalanceLabel.Text = Loc.GetString("atm-ui-balance", ("balance", _balance));
                ModeLabel.Text = Loc.GetString("atm-keypad-mode-amount");
                break;
            case AtmKeypadPhase.WaitingForPin:
                StatusLabel.Text = Loc.GetString("atm-keypad-enter-pin");
                BalanceLabel.Text = Loc.GetString("atm-ui-balance", ("balance", _balance));
                ModeLabel.Text = Loc.GetString("atm-keypad-mode-pin");
                break;
            case AtmKeypadPhase.ShowingResult:
                UpdateBufferLabel();
                return;
        }

        if (_showingResult)
            return;

        UpdateBufferLabel();
    }

    private void UpdateBufferLabel()
    {
        if (_phase == AtmKeypadPhase.WaitingForPin)
        {
            var masked = new string('*', _pinBuffer.Count);
            if (_pinBuffer.Count < 4 && _cursorVisible)
                masked += "_";
            else if (_pinBuffer.Count < 4 && !_cursorVisible)
                masked += " ";
            BufferLabel.Text = masked;
            return;
        }

        if (_phase == AtmKeypadPhase.WaitingForAmount || _phase == AtmKeypadPhase.WaitingForCard)
        {
            if (_amountBuffer.Count == 0)
            {
                BufferLabel.Text = _cursorVisible ? "_" : " ";
                return;
            }

            var amount = ParseBuffer(_amountBuffer);
            var text = $"{amount}¥";
            if (_cursorVisible)
                text += "_";
            BufferLabel.Text = text;
            return;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_powerSagTimer > 0)
        {
            _powerSagTimer -= args.DeltaSeconds;
            var sagAmount = Math.Clamp(_powerSagTimer / 0.15f, 0f, 1f);
            var brightness = 1f - (sagAmount * 0.6f);
            ScreenBackground.Modulate = new Color(brightness, brightness, brightness);
        }
        else
        {
            ScreenBackground.Modulate = Color.White;
        }

        if (_showingResult)
            return;

        _blinkTimer += args.DeltaSeconds;
        if (_blinkTimer >= 0.5f)
        {
            _blinkTimer = 0f;
            _cursorVisible = !_cursorVisible;
            UpdateDisplay();
        }

        if ((_phase == AtmKeypadPhase.WaitingForAmount && _amountBuffer.Count > 0) ||
            (_phase == AtmKeypadPhase.WaitingForPin && _pinBuffer.Count > 0))
        {
            _inactivityTimer += args.DeltaSeconds;
            if (_inactivityTimer >= 15f)
            {
                _audio.PlayPredicted(new SoundPathSpecifier("/Audio/Machines/button.ogg"), AtmOwner, User, new AudioParams().WithVolume(-6f).WithPitchScale(0.6f));
                _amountBuffer.Clear();
                _pinBuffer.Clear();
                _phase = _hasCard ? AtmKeypadPhase.WaitingForAmount : AtmKeypadPhase.WaitingForCard;
                _inactivityTimer = 0f;
                UpdateDisplay();
            }
        }
    }

    private static int ParseBuffer(List<int> buffer)
    {
        if (buffer.Count == 0)
            return 0;

        var result = 0;
        foreach (var digit in buffer)
        {
            result = result * 10 + digit;
        }
        return result;
    }
}
