// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Diagnostics.CodeAnalysis;
using Content.Client.UserInterface.Controls;
using Content.Shared.Lock;
using Content.Shared.Rounding;
using Content.Pirate.Shared.Nuclear.Turbine;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Pirate.Client.Nuclear.Turbine.UI;

/// <summary>
/// Client-side UI used to control a turbine.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TurbineWindow : FancyWindow
{
    // Dependencies
    [Dependency] private IEntityManager _ent = default!;
    private readonly LockSystem _lock;

    #region Variables
    //Colors for the RPM meter. (lit)
    private static readonly Color[] _speedColors = [
        Color.FromHex("#BB3232"),
        Color.FromHex("#BB3232"),
        Color.FromHex("#BB3232"),
        Color.FromHex("#C49438"),
        Color.FromHex("#C49438"),
        Color.FromHex("#C49438"),
        Color.FromHex("#B3BF28"),
        Color.FromHex("#B3BF28"),
        Color.FromHex("#B3BF28"),
        Color.FromHex("#6FC938"),
        Color.FromHex("#C49438"),
        Color.FromHex("#BB3232"),
    ];

    //Colors for the RPM meter. (unlit)
    private static readonly Color[] _speedColorsDim = new Color[12];

    // Style boxes for the RPM meter.
    private StyleBoxFlat[] _speedMeter;

    private int _speedLevel;
    private float _flowRate = -1;
    private float _statorLoad = -1;
    private EntityUid _owner;
    private bool _isMonitor;

    private bool _suppressSliderEvents;
    private bool _suppressStatorUpdate;
    private bool _suppressFlowUpdate;

    private readonly float _repeatDelay = 0.5f;
    private readonly Dictionary<Button, float> _repeatQueue = [];
    #endregion

    #region Events
    public event Action<float>? OnChangeFlowRate;
    public event Action<float>? OnChangeStatorLoad;
    public event Action? OnEmergencyShutdown;
    #endregion

    public TurbineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _lock = _ent.System<LockSystem>();

        InitRPMMeter();

        // Handle flow rate
        TurbineFlowRateLabel.OnFocusEnter += _ => _suppressFlowUpdate = true;
        TurbineFlowRateLabel.OnFocusExit += _ => FlowTextChanged();
        TurbineFlowRateLabel.OnTextEntered += _ => FlowTextChanged(true);

        TurbineFlowRateSlider.OnValueChanged += _ =>
        {
            if (!_suppressSliderEvents)
                OnChangeFlowRate?.Invoke(TurbineFlowRateSlider.Value);
        };
        FlowRateDecrease.OnPressed += _ => OnChangeFlowRate?.Invoke(_flowRate - 100);
        FlowRateDecrease.OnButtonDown += _ => _repeatQueue[FlowRateDecrease] = _repeatDelay;
        FlowRateDecrease.OnButtonUp += _ => _repeatQueue.Remove(FlowRateDecrease);

        FlowRateIncrease.OnPressed += _ => OnChangeFlowRate?.Invoke(_flowRate + 100);
        FlowRateIncrease.OnButtonDown += _ => _repeatQueue[FlowRateIncrease] = _repeatDelay;
        FlowRateIncrease.OnButtonUp += _ => _repeatQueue.Remove(FlowRateIncrease);

        // Handle stator load
        TurbineStatorLoadLabel.OnFocusEnter += _ => _suppressStatorUpdate = true;
        TurbineStatorLoadLabel.OnFocusExit += _ => StatorTextChanged();
        TurbineStatorLoadLabel.OnTextEntered += _ => StatorTextChanged(true);

        StatorLoadDecreaseLarge.OnPressed += _ => OnChangeStatorLoad?.Invoke(_statorLoad - 1000);
        StatorLoadDecreaseLarge.OnButtonDown += _ => _repeatQueue[StatorLoadDecreaseLarge] = _repeatDelay;
        StatorLoadDecreaseLarge.OnButtonUp += _ => _repeatQueue.Remove(StatorLoadDecreaseLarge);

        StatorLoadDecrease.OnPressed += _ => OnChangeStatorLoad?.Invoke(_statorLoad - 100);
        StatorLoadDecrease.OnButtonDown += _ => _repeatQueue[StatorLoadDecrease] = _repeatDelay;
        StatorLoadDecrease.OnButtonUp += _ => _repeatQueue.Remove(StatorLoadDecrease);

        StatorLoadIncrease.OnPressed += _ => OnChangeStatorLoad?.Invoke(_statorLoad + 100);
        StatorLoadIncrease.OnButtonDown += _ => _repeatQueue[StatorLoadIncrease] = _repeatDelay;
        StatorLoadIncrease.OnButtonUp += _ => _repeatQueue.Remove(StatorLoadIncrease);

        StatorLoadIncreaseLarge.OnPressed += _ => OnChangeStatorLoad?.Invoke(_statorLoad + 1000);
        StatorLoadIncreaseLarge.OnButtonDown += _ => _repeatQueue[StatorLoadIncreaseLarge] = _repeatDelay;
        StatorLoadIncreaseLarge.OnButtonUp += _ => _repeatQueue.Remove(StatorLoadIncreaseLarge);

        EmergencyShutdown.OnPressed += _ => OnEmergencyShutdown?.Invoke();

        CTabContainer.SetTabTitle(0, Loc.GetString("comp-turbine-ui-tab-main"));
        CTabContainer.SetTabTitle(1, Loc.GetString("comp-turbine-ui-tab-parts"));

        return;

        void FlowTextChanged(bool suppress = false)
        {
            if (float.TryParse(TurbineFlowRateLabel.Text, out var num) && !float.IsNaN(num))
                OnChangeFlowRate?.Invoke(num);
            _suppressFlowUpdate = suppress;
        }

        void StatorTextChanged(bool suppress = false)
        {
            if (float.TryParse(TurbineStatorLoadLabel.Text, out var num) && !float.IsNaN(num))
                OnChangeStatorLoad?.Invoke(num);
            _suppressStatorUpdate = suppress;
        }
    }

    #region Graphics
    public void SetEntity(EntityUid owner, bool isMonitor)
    {
        _owner = owner;
        _isMonitor = isMonitor;

        this.SetInfoFromEntity(_ent, owner);

        if (!isMonitor)
            EntityView.SetEntity(owner);

        UpdateLock();
    }

    [MemberNotNull(nameof(_speedMeter))]
    public void InitRPMMeter()
    {
        _speedMeter = new StyleBoxFlat[_speedColors.Length];

        for (var i = _speedColors.Length - 1; i >= 0; i--)
        {
            _speedColorsDim[i] = DimGaugeColor(_speedColors[i]);
            var styleBox = new StyleBoxFlat();
            _speedMeter[i] = styleBox;

            for (var j = 0; j < RPMMeter.Columns; j++)
            {
                var control = new PanelContainer
                {
                    Margin = new Thickness(2),
                    PanelOverride = styleBox,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                };
                RPMMeter.AddChild(control);
            }
        }
    }

    private static Color DimGaugeColor(Color color)
    {
        var hsv = Color.ToHsv(color);
        hsv.Z /= 5;
        return Color.FromHsv(hsv);
    }

    public void Update(TurbineBuiState state)
    {
        UpdateIndicators(state);

        if (state.FlowRate != _flowRate)
        {
            _flowRate = state.FlowRate;
            if (!_suppressFlowUpdate)
                TurbineFlowRateLabel.Text = Math.Round(_flowRate).ToString();
        }
        if (state.StatorLoad != _statorLoad)
        {
            _statorLoad = state.StatorLoad;
            if (!_suppressStatorUpdate)
                TurbineStatorLoadLabel.Text = Math.Round(_statorLoad).ToString();
        }

        _suppressSliderEvents = true;
        TurbineFlowRateSlider.MaxValue = state.MaximumFlowRate;
        TurbineFlowRateSlider.Value = state.FlowRate;
        _suppressSliderEvents = false;
        EmergencyShutdown.Disabled = state.FlowRate <= 0f;

        _speedLevel = ContentHelpers.RoundToNearestLevels(state.Rpm, state.BestRpm * 1.2, _speedMeter.Length);

        if (_isMonitor)
            EntityView.SetPrototype(state.TurbinePrototypeId);

        BladeEntityView.SetPrototype(state.Blade?.PrototypeId);
        BladeInfo.Visible = state.Blade != null;
        if (state.Blade is { } blade)
        {
            BladeInfoName.Text = blade.Name;
            var integrity = state.MaximumBladeHealth > 0
                ? Math.Round(state.BladeHealth * 100.0 / state.MaximumBladeHealth)
                : 0;
            BladeInfoIntegrity.Text = $"{integrity}%";

            var maximumRpm = state.BestRpm * 1.2;
            var stress = maximumRpm > 0
                ? (int) Math.Round(state.Rpm * 100f / maximumRpm)
                : 0;
            BladeInfoStress.Text = $"{stress}%";
        }

        StatorEntityView.SetPrototype(state.Stator?.PrototypeId);
        StatorInfo.Visible = state.Stator != null;
        if (state.Stator is { } stator)
        {
            StatorInfoName.Text = stator.Name;
            StatorInfoPotential.Text = Loc.GetString("comp-turbine-ui-power", ("power", state.GeneratedPower));
            StatorInfoSupply.Text = Loc.GetString("comp-turbine-ui-power", ("power", state.SuppliedPower));
        }

        UpdateLock();
    }

    private void UpdateLock()
    {
        var locked = _lock.IsLocked(_owner);
        Inputs.Visible = !locked;
        LockedMessage.Visible = locked;
    }

    private void UpdateIndicators(TurbineBuiState state)
    {
        string Lit(bool b)
            => b ? "lit.png" : "dim.png";

        var root = "/Textures/_Pirate/Nuclear/Structures/Power/Generation/FissionGenerator/indicator_lamps/";
        TurbineOverspeed.TexturePath = $"{root}red{Lit(state.Overspeed)}";
        TurbineOvertemp.TexturePath = $"{root}red{Lit(state.Overtemp)}";
        TurbineStalling.TexturePath = $"{root}amber{Lit(state.Stalling)}";
        TurbineUndertemp.TexturePath = $"{root}blue{Lit(state.Undertemp)}";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateLock();

        for (var i = 0; i < _speedMeter.Length; i++)
        {
            var box = _speedMeter[i];
            box.BackgroundColor = (_speedLevel > i ? _speedColors : _speedColorsDim)[i];
        }

        foreach (var (button, time) in _repeatQueue)
        {
            if (time > 0)
            {
                _repeatQueue[button] -= args.DeltaSeconds;
                continue;
            }

            _repeatQueue[button] = _repeatDelay;

            // TODO: something better holy shit
            switch (button)
            {
                case var _ when button == FlowRateDecrease:
                    OnChangeFlowRate?.Invoke(_flowRate - 100);
                    break;
                case var _ when button == FlowRateIncrease:
                    OnChangeFlowRate?.Invoke(_flowRate + 100);
                    break;
                case var _ when button == StatorLoadDecreaseLarge:
                    OnChangeStatorLoad?.Invoke(_statorLoad - 1000);
                    break;
                case var _ when button == StatorLoadDecrease:
                    OnChangeStatorLoad?.Invoke(_statorLoad - 100);
                    break;
                case var _ when button == StatorLoadIncrease:
                    OnChangeStatorLoad?.Invoke(_statorLoad + 100);
                    break;
                case var _ when button == StatorLoadIncreaseLarge:
                    OnChangeStatorLoad?.Invoke(_statorLoad + 1000);
                    break;
            }
        }
    }
    #endregion
}
