// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Pirate.Shared.Billiards;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.Billiards;

[GenerateTypedNameReferences]
public sealed partial class BilliardTableWindow : FancyWindow
{
    public event Action? OnPyramidPressed;
    public event Action? OnAmericanPoolPressed;
    public event Action? OnStoragePressed;

    public BilliardTableWindow()
    {
        RobustXamlLoader.Load(this);

        PyramidButton.OnPressed += _ => OnPyramidPressed?.Invoke();
        AmericanPoolButton.OnPressed += _ => OnAmericanPoolPressed?.Invoke();
        StorageButton.OnPressed += _ => OnStoragePressed?.Invoke();
    }

    public void UpdateState(BilliardTableBuiState state)
    {
        BallCountLabel.Text = Loc.GetString(
            "billiard-table-window-ball-count",
            ("count", state.BallCount),
            ("required", state.RequiredBallCount));

        StatusLabel.Text = Loc.GetString(GetStatusMessage(state));
    }

    private static string GetStatusMessage(BilliardTableBuiState state)
    {
        if (!state.Anchored)
            return "billiard-table-window-status-not-anchored";

        if (!state.SurfaceClear)
            return "billiard-table-window-status-surface-occupied";

        if (state.BallCount < state.RequiredBallCount)
            return "billiard-table-window-status-not-enough-balls";

        return "billiard-table-window-status-ready";
    }
}
