// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Pirate.Shared.Index;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Pirate.Client.Index;

[GenerateTypedNameReferences]
public sealed partial class IndexPagerWindow : DefaultWindow
{
    private static readonly Color TextColor = Color.FromHex("#E6E8EE");
    private static readonly Color PrescriptionColor = Color.FromHex("#F2D3A0");

    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private static readonly ResPath IndexLogoPath = new("/Textures/_Pirate/Interface/Misc/index.rsi");

    public IndexPagerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        IndexLogo.Texture = _resourceCache.GetResource<RSIResource>(IndexLogoPath).RSI["index"].Frame0;
    }

    public void UpdateState(IndexPagerBoundUserInterfaceState state)
    {
        KarmaLabel.Text = Loc.GetString("index-karma-label", ("karma", state.KarmicConsequence));
        MemberNameLabel.Text = state.Bound
            ? Loc.GetString("index-pager-member-label", ("name", state.MemberName))
            : Loc.GetString("index-pager-unbound");

        PrescriptionList.RemoveAllChildren();
        if (state.Prescriptions.Count == 0)
        {
            var empty = new RichTextLabel();
            empty.SetMessage(FormattedMessage.FromUnformatted(Loc.GetString("index-pager-no-prescriptions")), TextColor);
            empty.StyleClasses.Add("LabelSubText");
            PrescriptionList.AddChild(empty);
            return;
        }

        foreach (var prescription in state.Prescriptions)
        {
            var label = new RichTextLabel();
            label.SetMessage(FormattedMessage.FromUnformatted(prescription), PrescriptionColor);
            PrescriptionList.AddChild(label);
        }
    }
}
