using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.LightPaint;

[GenerateTypedNameReferences]
public sealed partial class LightPaintWindow : FancyWindow
{
    // tgstation crayon palette.
    private static readonly Color[] CrayonPresets =
    {
        Color.FromHex("#DA0000"), // red
        Color.FromHex("#FF9300"), // orange
        Color.FromHex("#FFF200"), // yellow
        Color.FromHex("#A8E61D"), // green
        Color.FromHex("#00B7EF"), // blue
        Color.FromHex("#DA00FF"), // purple
        Color.FromHex("#1C1C1C"), // black
        Color.White,
    };

    // Crystal light tube colours.
    private static readonly Color[] BulbPresets =
    {
        Color.FromHex("#fb4747"), // red
        Color.FromHex("#ff8227"), // orange
        Color.FromHex("#ffde46"), // yellow
        Color.FromHex("#52ff39"), // green
        Color.FromHex("#47f8ff"), // cyan
        Color.FromHex("#39a1ff"), // blue
        Color.FromHex("#800080"), // deep purple
        Color.FromHex("#ff66cc"), // pink
    };

    private static readonly Color Accent = Color.FromHex("#4f93d6");
    private static readonly Color LineSoft = Color.FromHex("#2b313d");

    private const int SwatchSize = 30;
    private const int SelectedBorder = 2;

    private readonly List<(StyleBoxFlat Border, Color Color)> _swatches = new();

    // Prevent slider updates from re-triggering selection.
    private bool _updating;

    public event Action<Color>? OnColorSelected;

    public LightPaintWindow()
    {
        RobustXamlLoader.Load(this);

        Swatches.AddChild(BuildRow(CrayonPresets, topRow: true));
        Swatches.AddChild(BuildRow(BulbPresets, topRow: false));

        ColorSelector.OnColorChanged += OnPickerChanged;
    }

    private BoxContainer BuildRow(Color[] colors, bool topRow)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, topRow ? 4 : 0),
        };

        foreach (var color in colors)
        {
            var border = new StyleBoxFlat
            {
                BackgroundColor = LineSoft,
                BorderColor = Accent,
                BorderThickness = new Thickness(0),
            };

            var swatch = color;
            var button = new Button
            {
                MinSize = new Vector2(SwatchSize, SwatchSize),
                ModulateSelfOverride = color,
            };
            button.OnPressed += _ => SelectColor(swatch, notify: true);

            var panel = new PanelContainer
            {
                PanelOverride = border,
                Margin = new Thickness(2, 0),
            };
            panel.AddChild(button);

            row.AddChild(panel);
            _swatches.Add((border, color));
        }

        return row;
    }

    private void OnPickerChanged(Color color)
    {
        if (_updating)
            return;

        UpdateSelection(color);
        OnColorSelected?.Invoke(color);
    }

    private void SelectColor(Color color, bool notify)
    {
        // Send one update after the sliders finish changing.
        _updating = true;
        ColorSelector.Color = color;
        _updating = false;

        UpdateSelection(color);

        if (notify)
            OnColorSelected?.Invoke(color);
    }

    private void UpdateSelection(Color color)
    {
        foreach (var (border, swatch) in _swatches)
        {
            border.BorderThickness = new Thickness(Matches(swatch, color) ? SelectedBorder : 0);
        }
    }

    // HSV round-trips can vary slightly; compare RGB bytes.
    private static bool Matches(Color a, Color b)
    {
        return a.RByte == b.RByte && a.GByte == b.GByte && a.BByte == b.BByte;
    }

    public void SetColor(Color color)
    {
        SelectColor(color, notify: false);
    }
}
