// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Pirate.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class DetomatixUiFragment : BoxContainer
{
    public event Action<uint>? OnDetonatePressed;

    private DetomatixUiState? _state;
    private string _filter = string.Empty;

    public DetomatixUiFragment()
    {
        RobustXamlLoader.Load(this);
        StyleChrome();

        SearchBar.PlaceHolder = Loc.GetString("detomatix-search-placeholder");
        SearchBar.OnTextChanged += args =>
        {
            _filter = args.Text.Trim();
            Rebuild();
        };
    }

    private void StyleChrome()
    {
        RootPanel.PanelOverride = DetomatixPalette.Band(DetomatixPalette.Panel,
            DetomatixPalette.Line,
            new Thickness(1));

        var header = DetomatixPalette.Band(DetomatixPalette.Head,
            DetomatixPalette.LineSoft,
            new Thickness(0, 0, 0, 1));
        SetPadding(header, 13, 9);
        HeaderPanel.PanelOverride = header;

        TitleLabel.FontColorOverride = DetomatixPalette.Text;
        TitleLabel.StyleClasses.Add("LabelHeading");
        ChargesCounter.FontColorOverride = DetomatixPalette.Accent;
        ChargesCounter.StyleClasses.Add("LabelHeading");

        ChargesCaption.FontColorOverride = DetomatixPalette.TextDim;
        ChargesCaption.StyleClasses.Add("LabelSubText");

        ChargesBar.BackgroundStyleBoxOverride = DetomatixPalette.Fill(DetomatixPalette.Track);
        ChargesBar.ForegroundStyleBoxOverride = DetomatixPalette.Fill(DetomatixPalette.Accent);
        ChargesBar.MinValue = 0f;

        SearchBar.StyleBoxOverride = DetomatixPalette.Band(DetomatixPalette.RowAlt,
            DetomatixPalette.Line,
            new Thickness(1),
            padding: 6);

        EmptyRule.PanelOverride = DetomatixPalette.Fill(DetomatixPalette.Accent);
        EmptyTitle.FontColorOverride = DetomatixPalette.TextDim;
        EmptyHint.FontColorOverride = DetomatixPalette.TextFaint;
        EmptyHint.StyleClasses.Add("LabelSubText");

        var hint = DetomatixPalette.Band(DetomatixPalette.Head,
            DetomatixPalette.LineSoft,
            new Thickness(0, 1, 0, 0));
        SetPadding(hint, 13, 7);
        HintBar.PanelOverride = hint;

        HintText.FontColorOverride = DetomatixPalette.TextFaint;
        HintText.StyleClasses.Add("LabelSubText");
        HintBrand.FontColorOverride = DetomatixPalette.TextFaint;
        HintBrand.StyleClasses.Add("LabelSubText");
    }

    private static void SetPadding(StyleBox box, float horizontal, float vertical)
    {
        box.ContentMarginLeftOverride = horizontal;
        box.ContentMarginRightOverride = horizontal;
        box.ContentMarginTopOverride = vertical;
        box.ContentMarginBottomOverride = vertical;
    }

    public void UpdateState(DetomatixUiState state)
    {
        _state = state;

        ChargesCounter.Text = $"{state.Charges} / {state.MaxCharges}";
        ChargesCounter.FontColorOverride = state.Charges > 0
            ? DetomatixPalette.Accent
            : DetomatixPalette.Zero;

        ChargesValue.Text = Loc.GetString("detomatix-charges", ("charges", state.Charges));
        ChargesValue.FontColorOverride = state.Charges > 0
            ? DetomatixPalette.Accent
            : DetomatixPalette.Zero;

        ChargesBar.MaxValue = Math.Max(state.MaxCharges, 1);
        ChargesBar.Value = state.Charges;

        Rebuild();
    }

    private void Rebuild()
    {
        Entries.RemoveAllChildren();
        ListCaption.RemoveAllChildren();

        if (_state is not { } state)
            return;

        var targets = Filter(state.Targets);
        var filtering = !string.IsNullOrEmpty(_filter);

        SearchBar.Visible = state.Targets.Count > 0;
        ListSection.Visible = targets.Count > 0;
        EmptyState.Visible = targets.Count == 0;

        if (targets.Count == 0)
        {
            EmptyTitle.Text = Loc.GetString(filtering ? "detomatix-no-matches" : "detomatix-no-targets");
            EmptyHint.Text = filtering
                ? Loc.GetString("detomatix-no-matches-hint", ("filter", _filter))
                : Loc.GetString("detomatix-no-targets-hint");
            return;
        }

        ListCaption.AddChild(DetomatixPalette.Eyebrow(Loc.GetString("detomatix-list-caption")));
        var count = DetomatixPalette.Eyebrow(
            Loc.GetString("detomatix-list-count", ("count", targets.Count)));
        count.HorizontalExpand = true;
        count.HorizontalAlignment = HAlignment.Right;
        ListCaption.AddChild(count);

        for (var i = 0; i < targets.Count; i++)
        {
            Entries.AddChild(new TargetRow(targets[i], i % 2 == 1, state.Charges > 0, OnDetonatePressed));
        }
    }

    private List<DetomatixTarget> Filter(List<DetomatixTarget> targets)
    {
        if (string.IsNullOrEmpty(_filter))
            return targets;

        return targets.Where(t =>
                t.Name.Contains(_filter, StringComparison.OrdinalIgnoreCase) ||
                t.Location.Contains(_filter, StringComparison.OrdinalIgnoreCase) ||
                (t.JobTitle?.Contains(_filter, StringComparison.OrdinalIgnoreCase) ?? false) ||
                $"{t.Number:D4}".Contains(_filter, StringComparison.OrdinalIgnoreCase))
            .ToList();
    }

    private sealed class TargetRow : PanelContainer
    {
        private bool _confirming;

        public TargetRow(DetomatixTarget target, bool banded, bool hasCharges, Action<uint>? onDetonate)
        {
            HorizontalExpand = true;

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var text = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            text.AddChild(new Label
            {
                Text = target.Name,
                FontColorOverride = DetomatixPalette.Text,
            });

            var detail = string.IsNullOrWhiteSpace(target.JobTitle)
                ? Loc.GetString("detomatix-target", ("number", $"#{target.Number:D4}"))
                : Loc.GetString("detomatix-target-with-job",
                    ("number", $"#{target.Number:D4}"),
                    ("job", target.JobTitle));

            text.AddChild(new Label
            {
                Text = detail,
                FontColorOverride = DetomatixPalette.TextFaint,
                StyleClasses = { "LabelSubText" },
            });

            text.AddChild(new Label
            {
                Text = target.Location,
                FontColorOverride = DetomatixPalette.TextDim,
                StyleClasses = { "LabelSubText" },
            });

            row.AddChild(text);
            row.AddChild(BuildAction(target, hasCharges, onDetonate));
            AddChild(row);

            StyleRow(target, banded);
        }

        private Control BuildAction(DetomatixTarget target, bool hasCharges, Action<uint>? onDetonate)
        {
            if (target.Armed)
            {
                return new Label
                {
                    Text = Loc.GetString("detomatix-armed-status"),
                    FontColorOverride = DetomatixPalette.Bad,
                    VerticalAlignment = VAlignment.Center,
                    Margin = new Thickness(8, 0, 0, 0),
                };
            }

            var button = new Button
            {
                Text = Loc.GetString("detomatix-detonate-button"),
                MinWidth = 104,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(8, 0, 0, 0),
                Disabled = !hasCharges,
            };

            var normal = DetomatixPalette.Button(DetomatixPalette.DangerBg, DetomatixPalette.DangerBorder);
            var hovered = DetomatixPalette.Button(DetomatixPalette.DangerBgHover, DetomatixPalette.DangerBorder);
            button.StyleBoxOverride = normal;
            button.Label.FontColorOverride = DetomatixPalette.DangerText;
            button.ModulateSelfOverride = hasCharges ? null : Color.White.WithAlpha(0.4f);

            button.OnMouseEntered += _ => button.StyleBoxOverride = hovered;
            button.OnMouseExited += _ => button.StyleBoxOverride = normal;

            button.OnPressed += _ =>
            {
                // Require confirmation before detonating.
                if (!_confirming)
                {
                    _confirming = true;
                    button.Text = Loc.GetString("detomatix-confirm-button");
                    normal = DetomatixPalette.Button(DetomatixPalette.ConfirmBg, DetomatixPalette.ConfirmBorder);
                    hovered = DetomatixPalette.Button(DetomatixPalette.ConfirmBgHover, DetomatixPalette.ConfirmBorder);
                    button.StyleBoxOverride = normal;
                    button.Label.FontColorOverride = DetomatixPalette.ConfirmText;
                    return;
                }

                button.Disabled = true;
                onDetonate?.Invoke(target.Number);
            };

            return button;
        }

        private void StyleRow(DetomatixTarget target, bool banded)
        {
            if (target.Armed)
            {
                PanelOverride = DetomatixPalette.Band(DetomatixPalette.AccentFill,
                    DetomatixPalette.Accent,
                    new Thickness(3, 1, 1, 1));
                ApplyRowPadding(PanelOverride);
                Margin = new Thickness(0, 3, 0, 3);
                return;
            }

            var background = banded ? DetomatixPalette.RowAlt : Color.Transparent;

            var normal = DetomatixPalette.Band(background,
                DetomatixPalette.LineSoft,
                new Thickness(0, 0, 0, 1));
            var hovered = DetomatixPalette.Band(DetomatixPalette.RowHover,
                DetomatixPalette.LineSoft,
                new Thickness(0, 0, 0, 1));

            ApplyRowPadding(normal);
            ApplyRowPadding(hovered);
            DetomatixPalette.HoverSwap(this, this, normal, hovered);
        }

        private static void ApplyRowPadding(StyleBox box)
        {
            box.ContentMarginLeftOverride = 8;
            box.ContentMarginRightOverride = 8;
            box.ContentMarginTopOverride = 7;
            box.ContentMarginBottomOverride = 7;
        }
    }
}
