// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterWindow : DefaultWindow
{
    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
        MinWidth = 520; // Pirate: keep the skills overview readable at its initial size.
        CharacterInfoTabs.SetTabTitle(0, Loc.GetString("character-info-overview")); // Pirate: Starlight character descriptions.
        CharacterInfoTabs.SetTabTitle(1, Loc.GetString("character-info-ic"));
        CharacterInfoTabs.SetTabTitle(2, Loc.GetString("character-info-ooc"));
        CharacterInfoTabs.SetTabTitle(3, Loc.GetString("knowledge-character-tab")); // Pirate
    }
}
