# Jumpsuit - комбінезон
- type: loadout
  id: HeadOfSecurityBlueSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtSecurityHosBlue

# Head - капелюхи
- type: loadout
  id: HeadOfSecurityBunnyears
  equipment:
    head: ClothingHeadHatBunnyearsHOS
