// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Pirate.Knowledge;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Pirate.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeProfileEditor : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _systems = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public event Action<KnowledgeProfile>? OnApply;

    private SharedKnowledgeSystem _knowledge = default!;
    private KnowledgeProfilePrototype? _speciesProfile;
    private KnowledgeProfile _profile = new();
    private bool _modified;

    public KnowledgeProfileEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _knowledge = _systems.GetEntitySystem<SharedKnowledgeSystem>();

        SaveButton.OnPressed += _ => Apply();
        ResetButton.OnPressed += _ => ResetSelection();
        SetButtons();
    }

    public void SetProfile(ProtoId<SpeciesPrototype> speciesId, KnowledgeProfile profile)
    {
        if (!_prototypes.TryIndex(speciesId, out var species) ||
            !_prototypes.TryIndex(species.Knowledge, out _speciesProfile))
        {
            _speciesProfile = null;
            _profile = new KnowledgeProfile();
            _modified = false;
            Skills.RemoveAllChildren();
            PointsLabel.Text = Loc.GetString("knowledge-editor-profile-unavailable");
            SetButtons();
            return;
        }

        _profile = new KnowledgeProfile(profile);
        _modified = false;
        Rebuild();
    }

    private void Rebuild()
    {
        Skills.RemoveAllChildren();
        if (_speciesProfile is null)
            return;

        var entries = _knowledge.AllKnowledges
            .Where(pair => pair.Value.Costs is not null)
            .OrderBy(pair => Loc.GetString(_prototypes.Index(pair.Value.Category).Name))
            .ThenBy(pair => _prototypes.Index<EntityPrototype>(pair.Key).Name)
            .ToList();

        ProtoId<KnowledgeCategoryPrototype>? currentCategory = null;
        foreach (var (id, component) in entries)
        {
            if (currentCategory != component.Category)
            {
                currentCategory = component.Category;
                Skills.AddChild(new Label
                {
                    Text = Loc.GetString(_prototypes.Index(component.Category).Name),
                    StyleClasses = { "LabelHeading" },
                    Margin = new Thickness(0, 8, 0, 2),
                });
            }

            AddSkillRow(id, component);
        }

        UpdatePoints();
        SetButtons();
    }

    private void AddSkillRow(EntProtoId id, KnowledgeComponent component)
    {
        var costs = component.Costs!;
        var prototype = _prototypes.Index<EntityPrototype>(id);
        var racialBase = _speciesProfile!.Profile.Mastery?.GetValueOrDefault(id) ?? 0;
        var selected = _profile.Mastery?.GetValueOrDefault(id) ?? 0;
        var mastery = racialBase + selected;

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            MinHeight = 32,
            ToolTip = prototype.Description,
            MouseFilter = MouseFilterMode.Pass,
        };

        var name = new Label
        {
            Text = prototype.Name,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        var decrease = new Button
        {
            Text = "-",
            MinWidth = 34,
            ToolTip = Loc.GetString("knowledge-editor-decrease"),
        };
        var masteryLabel = new Label
        {
            MinWidth = 190,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
        var increase = new Button
        {
            Text = "+",
            MinWidth = 34,
            ToolTip = Loc.GetString("knowledge-editor-increase"),
        };

        void RefreshRow()
        {
            selected = _profile.Mastery?.GetValueOrDefault(id) ?? 0;
            mastery = racialBase + selected;
            var cost = selected >= 0 && selected < costs.Length ? costs[selected] : 0;
            masteryLabel.Text = Loc.GetString(
                "knowledge-editor-mastery",
                ("mastery", SharedKnowledgeSystem.GetMasteryString(mastery)),
                ("cost", cost));
            decrease.Disabled = selected <= 0;
            increase.Disabled = mastery >= costs.Length - 1 || selected >= costs.Length - 1;
            var color = mastery <= 0 ? Color.Gray : Color.White;
            name.Modulate = color;
            masteryLabel.Modulate = color;
        }

        void Change(int difference)
        {
            var nextSelected = selected + difference;
            var nextMastery = racialBase + nextSelected;
            if (nextSelected < 0 || nextSelected >= costs.Length || nextMastery >= costs.Length)
                return;

            _profile.Mastery ??= new Dictionary<EntProtoId, int>();
            if (nextSelected == 0)
                _profile.Mastery.Remove(id);
            else
                _profile.Mastery[id] = nextSelected;

            _modified = true;
            RefreshRow();
            UpdatePoints();
            SetButtons();
        }

        decrease.OnPressed += _ => Change(-1);
        increase.OnPressed += _ => Change(1);
        RefreshRow();

        row.AddChild(name);
        row.AddChild(decrease);
        row.AddChild(masteryLabel);
        row.AddChild(increase);
        Skills.AddChild(row);
    }

    private void UpdatePoints()
    {
        if (_speciesProfile is null)
            return;

        var remaining = _speciesProfile.PointsLimit - _knowledge.ProfileCost(_profile);
        PointsLabel.Text = Loc.GetString("knowledge-editor-points", ("points", remaining));
        PointsLabel.FontColorOverride = remaining < 0 ? Color.Red : Color.White;
    }

    private void SetButtons()
    {
        var valid = _speciesProfile is not null &&
                    _speciesProfile.PointsLimit - _knowledge.ProfileCost(_profile) >= 0;
        SaveButton.Disabled = !_modified || !valid;
        ResetButton.Disabled = _speciesProfile is null ||
                               (!_modified && (_profile.Mastery is null || _profile.Mastery.Count == 0));
    }

    private void Apply()
    {
        if (SaveButton.Disabled)
            return;

        OnApply?.Invoke(new KnowledgeProfile(_profile));
        _modified = false;
        SetButtons();
    }

    private void ResetSelection()
    {
        _profile = new KnowledgeProfile();
        _modified = true;
        Rebuild();
    }
}
