// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Pirate.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Pirate.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeAdminWindow : DefaultWindow
{
    public event Action<Dictionary<string, KnowledgeAdminEdit>>? ApplyRequested;
    public event Action? RefreshRequested;

    private readonly Dictionary<string, SkillRow> _rows = new();
    private readonly List<CategoryRows> _categories = new();
    private KnowledgeAdminEuiState? _state;

    public KnowledgeAdminWindow()
    {
        RobustXamlLoader.Load(this);

        SearchInput.OnTextChanged += _ => UpdateFilter();
        RefreshButton.OnPressed += _ => RefreshRequested?.Invoke();
        ResetButton.OnPressed += _ => ResetChanges();
        ApplyButton.OnPressed += _ => ApplyChanges();
        UpdateButtons();
    }

    public void SetState(KnowledgeAdminEuiState state)
    {
        _state = state;
        TargetLabel.Text = Loc.GetString("knowledge-admin-target", ("target", state.TargetName));
        RebuildSkills();
    }

    private void RebuildSkills()
    {
        SkillsBox.RemoveAllChildren();
        _rows.Clear();
        _categories.Clear();

        if (_state is null)
            return;

        foreach (var group in _state.Skills
                     .OrderBy(entry => entry.Category)
                     .ThenBy(entry => entry.Name)
                     .GroupBy(entry => entry.Category))
        {
            var category = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 5,
            };

            var header = new PanelContainer
            {
                StyleClasses = { KnowledgeStyleClasses.CategoryHeader },
                HorizontalExpand = true,
            };
            header.AddChild(new Label
            {
                Text = group.Key,
                StyleClasses = { KnowledgeStyleClasses.CategoryName },
            });
            category.AddChild(header);

            var entries = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 4,
            };
            var categoryRows = new CategoryRows(category);
            foreach (var entry in group)
            {
                var row = CreateSkillRow(entry);
                entries.AddChild(row.Control);
                categoryRows.Rows.Add(row);
                _rows.Add(entry.Prototype, row);
            }

            category.AddChild(entries);
            _categories.Add(categoryRows);
            SkillsBox.AddChild(category);
        }

        UpdateFilter();
        UpdateButtons();
    }

    private SkillRow CreateSkillRow(KnowledgeAdminEntry entry)
    {
        var control = new PanelContainer
        {
            StyleClasses = { KnowledgeStyleClasses.SkillRow },
            HorizontalExpand = true,
            ToolTip = entry.Description,
            MouseFilter = MouseFilterMode.Pass,
        };
        var contents = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
        };

        var summary = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        summary.AddChild(new Label
        {
            Text = entry.Name,
            StyleClasses = { KnowledgeStyleClasses.SkillName },
        });
        var details = new Label
        {
            StyleClasses = { KnowledgeStyleClasses.SkillDetails },
        };
        summary.AddChild(details);

        var level = new SpinBox
        {
            MinWidth = 210,
            IsValid = value => value is >= 0 and <= 100,
        };
        // Pirate: avoid collection-expression lowering to CollectionsMarshal.SetCount,
        // which is rejected by the client sandbox verifier.
        level.SetButtons(new List<int> { -10, -1 }, new List<int> { 1, 10 });
        level.OverrideValue(entry.LearnedLevel);

        var experience = new SpinBox
        {
            MinWidth = 145,
        };
        experience.InitDefaultButtons();

        var row = new SkillRow(entry, control, details, level, experience);
        experience.IsValid = value => value >= 0 && value <= row.MaxExperience;
        experience.OverrideValue(Math.Clamp(entry.Experience, 0, row.MaxExperience));

        level.ValueChanged += _ =>
        {
            row.RefreshLimits();
            UpdateButtons();
        };
        experience.ValueChanged += _ => UpdateButtons();

        contents.AddChild(summary);
        contents.AddChild(level);
        contents.AddChild(experience);
        control.AddChild(contents);
        row.RefreshLimits();
        return row;
    }

    private void UpdateFilter()
    {
        var filter = SearchInput.Text.Trim();
        var anyVisible = false;

        foreach (var category in _categories)
        {
            var categoryVisible = false;
            foreach (var row in category.Rows)
            {
                row.Control.Visible = filter.Length == 0 ||
                                      row.SearchText.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
                categoryVisible |= row.Control.Visible;
            }

            category.Control.Visible = categoryVisible;
            anyVisible |= categoryVisible;
        }

        SkillsScroll.Visible = anyVisible;
        EmptyLabel.Visible = !anyVisible;
    }

    private void ResetChanges()
    {
        foreach (var row in _rows.Values)
            row.Reset();

        UpdateButtons();
    }

    private void ApplyChanges()
    {
        var changes = _rows.Values
            .Where(row => row.Modified)
            .ToDictionary(
                row => row.Entry.Prototype,
                row => new KnowledgeAdminEdit(row.Level.Value, row.Experience.Value));

        if (changes.Count == 0)
            return;

        ApplyButton.Disabled = true;
        ApplyRequested?.Invoke(changes);
    }

    private void UpdateButtons()
    {
        var modified = _rows.Values.Count(row => row.Modified);
        var targetAvailable = _state?.Target is not null;
        PendingLabel.Text = modified == 0
            ? string.Empty
            : Loc.GetString("knowledge-admin-pending", ("count", modified));
        ResetButton.Disabled = modified == 0;
        ApplyButton.Disabled = modified == 0 || !targetAvailable;
    }

    private sealed class SkillRow
    {
        public readonly KnowledgeAdminEntry Entry;
        public readonly PanelContainer Control;
        public readonly SpinBox Level;
        public readonly SpinBox Experience;

        private readonly Label _details;

        public int MaxExperience => Level.Value < 100 && Entry.ExperienceCost > 0
            ? Entry.ExperienceCost - 1
            : 0;

        public bool Modified => Level.Value != Entry.LearnedLevel || Experience.Value != Entry.Experience;

        public string SearchText => $"{Entry.Name} {Entry.Category} {Entry.Prototype}";

        public SkillRow(
            KnowledgeAdminEntry entry,
            PanelContainer control,
            Label details,
            SpinBox level,
            SpinBox experience)
        {
            Entry = entry;
            Control = control;
            _details = details;
            Level = level;
            Experience = experience;
        }

        public void RefreshLimits()
        {
            if (Experience.Value > MaxExperience)
                Experience.OverrideValue(MaxExperience);

            var canGainExperience = MaxExperience > 0;
            Experience.LineEditDisabled = !canGainExperience;
            Experience.SetButtonDisabled(!canGainExperience);

            var effective = Math.Clamp(Level.Value + Entry.TemporaryLevel, 0, 100);
            var details = new List<string>
            {
                Loc.GetString(
                    "knowledge-character-level-mastery",
                    ("level", effective),
                    ("mastery", SharedKnowledgeSystem.GetMasteryString(
                        SharedKnowledgeSystem.GetMastery(effective)))),
            };

            if (Entry.TemporaryLevel != 0)
            {
                details.Add(Loc.GetString(
                    "knowledge-admin-temporary-level",
                    ("level", Entry.TemporaryLevel)));
            }

            if (!Entry.Exists)
                details.Add(Loc.GetString("knowledge-admin-not-learned"));
            if (Entry.Hidden)
                details.Add(Loc.GetString("knowledge-admin-hidden"));

            _details.Text = string.Join(" | ", details);
        }

        public void Reset()
        {
            Level.OverrideValue(Entry.LearnedLevel);
            RefreshLimits();
            Experience.OverrideValue(Math.Clamp(Entry.Experience, 0, MaxExperience));
        }
    }

    private sealed class CategoryRows(Control control)
    {
        public readonly Control Control = control;
        public readonly List<SkillRow> Rows = new();
    }
}
