// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Pirate.Knowledge;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Pirate.Knowledge.UI;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeTab : BoxContainer
{
    [Dependency] private readonly IEntitySystemManager _systems = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    private SharedKnowledgeSystem _knowledge = default!;
    private SpriteSystem _sprites = default!;

    public KnowledgeTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _knowledge = _systems.GetEntitySystem<SharedKnowledgeSystem>();
        _sprites = _systems.GetEntitySystem<SpriteSystem>();
    }

    public void UpdateKnowledgeTab(EntityUid player)
    {
        KnowledgeBox.RemoveAllChildren();

        var skills = _knowledge.GetAllKnowledge(player)?
            .Where(skill => !skill.Comp.Hidden)
            .Select(skill => (Skill: skill, Info: _knowledge.GetKnowledgeInfo(skill)))
            .OrderBy(data => Loc.GetString(_prototypes.Index(data.Skill.Comp.Category).Name))
            .ThenBy(data => data.Info.Name)
            .ToList();

        KnowledgePlaceholder.Visible = skills is null || skills.Count == 0;
        if (skills is null)
            return;

        ProtoId<KnowledgeCategoryPrototype>? currentCategory = null;
        BoxContainer? categorySkills = null;
        foreach (var (skill, info) in skills)
        {
            if (currentCategory != skill.Comp.Category)
            {
                currentCategory = skill.Comp.Category;
                var category = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    SeparationOverride = 5,
                };

                var header = new PanelContainer
                {
                    StyleClasses = { KnowledgeStyleClasses.CategoryHeader },
                    HorizontalExpand = true,
                };
                header.AddChild(new Label
                {
                    Text = Loc.GetString(_prototypes.Index(skill.Comp.Category).Name),
                    StyleClasses = { KnowledgeStyleClasses.CategoryName },
                });
                category.AddChild(header);

                categorySkills = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    SeparationOverride = 4,
                };
                category.AddChild(categorySkills);
                KnowledgeBox.AddChild(category);
            }

            categorySkills!.AddChild(CreateSkillRow(info));
        }
    }

    private Control CreateSkillRow(KnowledgeInfo info)
    {
        var row = new PanelContainer
        {
            StyleClasses = { KnowledgeStyleClasses.SkillRow },
            HorizontalExpand = true,
            ToolTip = info.Description,
            MouseFilter = MouseFilterMode.Pass,
        };

        var body = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        var summary = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
        };

        if (info.Sprite is { } sprite)
        {
            summary.AddChild(new TextureRect
            {
                Texture = _sprites.Frame0(sprite),
                MinSize = new System.Numerics.Vector2(30, 30),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                VerticalAlignment = VAlignment.Center,
            });
        }

        var labels = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        labels.AddChild(new Label
        {
            Text = info.Name,
            StyleClasses = { KnowledgeStyleClasses.SkillName },
        });
        labels.AddChild(new Label
        {
            Text = Loc.GetString(
                "knowledge-character-level-mastery",
                ("level", info.NetLevel),
                ("mastery", SharedKnowledgeSystem.GetMasteryString(
                    SharedKnowledgeSystem.GetMastery(info.NetLevel)))),
            StyleClasses = { KnowledgeStyleClasses.SkillDetails },
        });
        summary.AddChild(labels);

        if (info.ExperienceCost > 0)
        {
            summary.AddChild(new Label
            {
                Text = Loc.GetString(
                    "knowledge-character-experience",
                    ("current", info.Experience),
                    ("required", info.ExperienceCost)),
                StyleClasses = { KnowledgeStyleClasses.SkillExperience },
                VerticalAlignment = VAlignment.Center,
            });
        }

        body.AddChild(summary);

        if (info.ExperienceCost > 0)
        {
            var progressBackground = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#15171C"),
                BorderColor = Color.FromHex("#3A3E48"),
                BorderThickness = new Thickness(1),
            };
            progressBackground.SetContentMarginOverride(StyleBox.Margin.Vertical, 3);

            var progressForeground = new StyleBoxFlat
            {
                BackgroundColor = info.Color,
            };
            progressForeground.SetContentMarginOverride(StyleBox.Margin.Vertical, 3);

            body.AddChild(new ProgressBar
            {
                MinValue = 0,
                MaxValue = info.ExperienceCost,
                Value = Math.Clamp(info.Experience, 0, info.ExperienceCost),
                HorizontalExpand = true,
                BackgroundStyleBoxOverride = progressBackground,
                ForegroundStyleBoxOverride = progressForeground,
            });
        }

        row.AddChild(body);
        return row;
    }
}
