// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Roles;
using Content.Pirate.Shared.Administration.JobSlots;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Pirate.Client.Administration.JobSlots;

[GenerateTypedNameReferences]
public sealed partial class JobSlotsWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly JobSystem _jobSystem;
    private readonly SpriteSystem _spriteSystem;
    private readonly Dictionary<ProtoId<JobPrototype>, JobSlotsEntry> _entries = new();
    private readonly List<JobSlotsDepartment> _departments = new();

    private List<JobSlotsStationData> _stations = new();
    private NetEntity? _selectedStation;
    private bool _refreshPending;
    private bool _stateInitialized;

    public event Action<NetEntity, ProtoId<JobPrototype>, int>? AdjustmentRequested;
    public event Action? RefreshRequested;

    public JobSlotsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _jobSystem = _entityManager.System<JobSystem>();
        _spriteSystem = _entityManager.System<SpriteSystem>();

        AdjustmentSpinBox.IsValid = value => value is > 0 and <= JobSlotsEuiConstants.MaxAdjustment;
        AdjustmentSpinBox.InitDefaultButtons();

        StationSelector.OnItemSelected += OnStationSelected;
        JobSearch.OnTextChanged += _ => UpdateSearch();
        RefreshButton.OnPressed += _ =>
        {
            _refreshPending = true;
            SetStatus(Loc.GetString("job-slots-status-refreshing"), Color.Gold);
            RefreshRequested?.Invoke();
        };
    }

    public void UpdateState(IReadOnlyList<JobSlotsStationData> stations)
    {
        var previousStation = _selectedStation;
        var stationListChanged = !_stateInitialized || !StationsMatch(stations);
        _stateInitialized = true;
        _stations = stations.ToList();

        if (stationListChanged)
            RebuildStationSelector(previousStation);

        StationSelector.Disabled = _stations.Count == 0;
        JobSearch.Editable = _stations.Count != 0;
        var selectedChanged = previousStation != _selectedStation;
        UpdateJobs(selectedChanged);

        if (_refreshPending)
        {
            _refreshPending = false;
            SetStatus(Loc.GetString("job-slots-status-refreshed"), Color.LightGreen);
        }
    }

    public void ShowResult(
        JobSlotsUpdateResult result,
        ProtoId<JobPrototype> jobId,
        int? slots)
    {
        var jobName = _prototypeManager.TryIndex<JobPrototype>(jobId, out var job)
            ? job.LocalizedName
            : jobId.Id;

        switch (result)
        {
            case JobSlotsUpdateResult.Success:
                SetStatus(
                    Loc.GetString("job-slots-status-success",
                        ("job", jobName),
                        ("slots", slots ?? 0)),
                    Color.LightGreen);
                break;
            case JobSlotsUpdateResult.Unlimited:
                SetStatus(
                    Loc.GetString("job-slots-status-unlimited", ("job", jobName)),
                    Color.Gold);
                break;
            case JobSlotsUpdateResult.InvalidAmount:
                SetStatus(Loc.GetString("job-slots-status-invalid-amount"), Color.OrangeRed);
                break;
            case JobSlotsUpdateResult.StationUnavailable:
                SetStatus(Loc.GetString("job-slots-status-station-unavailable"), Color.OrangeRed);
                break;
            case JobSlotsUpdateResult.JobUnavailable:
                SetStatus(
                    Loc.GetString("job-slots-status-job-unavailable", ("job", jobId.Id)),
                    Color.OrangeRed);
                break;
            case JobSlotsUpdateResult.AdjustmentFailed:
                SetStatus(
                    Loc.GetString("job-slots-status-failed", ("job", jobName)),
                    Color.OrangeRed);
                break;
        }
    }

    private void RebuildStationSelector(NetEntity? previousStation)
    {
        StationSelector.Clear();

        for (var index = 0; index < _stations.Count; index++)
            StationSelector.AddItem(_stations[index].Name, index);

        if (_stations.Count == 0)
        {
            StationSelector.AddItem(Loc.GetString("job-slots-station-none"), 0);
            _selectedStation = null;
            StationSelector.Disabled = true;
            return;
        }

        StationSelector.Disabled = false;
        var selectedIndex = previousStation is { } previous
            ? _stations.FindIndex(station => station.Station == previous)
            : -1;

        if (selectedIndex < 0)
            selectedIndex = 0;

        StationSelector.SelectId(selectedIndex);
        _selectedStation = _stations[selectedIndex].Station;
    }

    private bool StationsMatch(IReadOnlyList<JobSlotsStationData> stations)
    {
        if (_stations.Count != stations.Count)
            return false;

        for (var index = 0; index < stations.Count; index++)
        {
            if (_stations[index].Station != stations[index].Station ||
                _stations[index].Name != stations[index].Name)
            {
                return false;
            }
        }

        return true;
    }

    private void OnStationSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (args.Id < 0 || args.Id >= _stations.Count)
            return;

        StationSelector.SelectId(args.Id);
        _selectedStation = _stations[args.Id].Station;
        SetStatus(" ", Color.White);
        UpdateJobs(forceRebuild: true);
    }

    private void UpdateJobs(bool forceRebuild = false)
    {
        var station = GetSelectedStation();
        if (station == null)
        {
            DisposeJobControls();
            EmptyLabel.Text = Loc.GetString("job-slots-no-stations");
            EmptyLabel.Visible = true;
            return;
        }

        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>()
            .Where(job => job.SetPreference || station.Jobs.ContainsKey(job.ID))
            .ToList();
        var desiredJobs = jobs
            .Select(job => new ProtoId<JobPrototype>(job.ID))
            .ToHashSet();

        if (forceRebuild || !_entries.Keys.ToHashSet().SetEquals(desiredJobs))
            RebuildJobs(jobs);

        foreach (var (jobId, entry) in _entries)
        {
            var exists = station.Jobs.TryGetValue(jobId, out var slots);
            entry.UpdateSlots(exists, slots);
        }

        UpdateSearch();
    }

    private void RebuildJobs(List<JobPrototype> jobs)
    {
        DisposeJobControls();

        var groupedJobs = new Dictionary<string, (DepartmentPrototype? Department, List<JobPrototype> Jobs)>();

        foreach (var job in jobs)
        {
            var department = GetDepartment(job);
            var departmentId = department?.ID ?? string.Empty;

            if (!groupedJobs.TryGetValue(departmentId, out var group))
                group = (department, new List<JobPrototype>());

            group.Jobs.Add(job);
            groupedJobs[departmentId] = group;
        }

        var groups = groupedJobs.Values.ToList();
        groups.Sort((left, right) =>
        {
            if (left.Department == null)
                return right.Department == null ? 0 : 1;
            if (right.Department == null)
                return -1;
            return DepartmentUIComparer.Instance.Compare(left.Department, right.Department);
        });

        foreach (var (department, departmentJobs) in groups)
        {
            departmentJobs.Sort(JobUIComparer.Instance);

            var departmentName = department == null
                ? Loc.GetString("job-slots-department-other")
                : Loc.GetString(department.Name);
            var departmentColor = department?.Color ?? Color.Gray;
            var section = new JobSlotsDepartment(departmentName, departmentColor);

            foreach (var job in departmentJobs)
            {
                var entry = new JobSlotsEntry(job, departmentColor, _spriteSystem, _prototypeManager);
                entry.AdjustmentRequested += direction => RequestAdjustment(entry.Job, direction);
                section.AddEntry(entry);
                _entries.Add(entry.Job, entry);
            }

            _departments.Add(section);
            JobContainer.AddChild(section);
        }
    }

    private DepartmentPrototype? GetDepartment(JobPrototype job)
    {
        return _jobSystem.TryGetLowestWeightDepartment(job.ID, out var department)
            ? department
            : null;
    }

    private JobSlotsStationData? GetSelectedStation()
    {
        if (_selectedStation is not { } selected)
            return null;

        return _stations.FirstOrDefault(station => station.Station == selected);
    }

    private void RequestAdjustment(ProtoId<JobPrototype> job, int direction)
    {
        if (_selectedStation is not { } station)
            return;

        var amount = AdjustmentSpinBox.Value * direction;
        var jobName = _prototypeManager.TryIndex<JobPrototype>(job, out var prototype)
            ? prototype.LocalizedName
            : job.Id;

        SetStatus(Loc.GetString("job-slots-status-updating", ("job", jobName)), Color.Gold);
        AdjustmentRequested?.Invoke(station, job, amount);
    }

    private void UpdateSearch()
    {
        if (GetSelectedStation() == null)
        {
            EmptyLabel.Text = Loc.GetString("job-slots-no-stations");
            EmptyLabel.Visible = true;
            return;
        }

        var query = JobSearch.Text.Trim();
        var visibleEntries = 0;

        foreach (var entry in _entries.Values)
        {
            entry.Visible = entry.Matches(query);
            if (entry.Visible)
                visibleEntries++;
        }

        foreach (var department in _departments)
            department.UpdateVisibility();

        EmptyLabel.Text = _entries.Count == 0
            ? Loc.GetString("job-slots-no-jobs")
            : Loc.GetString("job-slots-no-results");
        EmptyLabel.Visible = visibleEntries == 0;
    }

    private void DisposeJobControls()
    {
        JobContainer.DisposeAllChildren();
        _entries.Clear();
        _departments.Clear();
    }

    private void SetStatus(string text, Color color)
    {
        StatusLabel.Text = text;
        StatusLabel.FontColorOverride = color;
    }
}
