// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.Administration.JobSlots;

[GenerateTypedNameReferences]
public sealed partial class JobSlotsDepartment : BoxContainer
{
    private readonly List<JobSlotsEntry> _entries = new();

    public JobSlotsDepartment(string name, Color color)
    {
        RobustXamlLoader.Load(this);

        DepartmentLabel.Text = name;
        AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
    }

    public void AddEntry(JobSlotsEntry entry)
    {
        _entries.Add(entry);
        EntriesContainer.AddChild(entry);
        UpdateVisibility();
    }

    public void UpdateVisibility()
    {
        var visibleCount = _entries.Count(entry => entry.Visible);
        Visible = visibleCount > 0;
        VisibleCountLabel.Text = visibleCount.ToString();
    }
}
