// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Pirate.Client.Administration.JobSlots;

[GenerateTypedNameReferences]
public sealed partial class JobSlotsEntry : PanelContainer
{
    private readonly string _localizedName;

    public ProtoId<JobPrototype> Job { get; }
    public event Action<int>? AdjustmentRequested;

    public JobSlotsEntry(
        JobPrototype job,
        Color departmentColor,
        SpriteSystem spriteSystem,
        IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);

        Job = job.ID;
        _localizedName = job.LocalizedName;

        JobNameLabel.Text = _localizedName;
        JobNameLabel.ToolTip = _localizedName;
        JobIdLabel.Text = job.ID;
        JobIdLabel.ToolTip = job.ID;
        DepartmentStripe.PanelOverride = new StyleBoxFlat { BackgroundColor = departmentColor };

        if (prototypeManager.TryIndex<JobIconPrototype>(job.Icon, out var jobIcon))
            JobIcon.Texture = spriteSystem.Frame0(jobIcon.Icon);

        DecreaseButton.OnPressed += _ => AdjustmentRequested?.Invoke(-1);
        IncreaseButton.OnPressed += _ => AdjustmentRequested?.Invoke(1);
    }

    public void UpdateSlots(bool exists, int? slots)
    {
        switch (exists, slots)
        {
            case (false, _):
                SlotsLabel.Text = Loc.GetString("job-slots-count-not-added");
                SlotsLabel.FontColorOverride = Color.Gray;
                DecreaseButton.Disabled = true;
                IncreaseButton.Disabled = false;
                break;
            case (true, null):
                SlotsLabel.Text = Loc.GetString("job-slots-count-unlimited");
                SlotsLabel.FontColorOverride = Color.Gold;
                DecreaseButton.Disabled = true;
                IncreaseButton.Disabled = true;
                break;
            case (true, 0):
                SlotsLabel.Text = "0";
                SlotsLabel.FontColorOverride = Color.OrangeRed;
                DecreaseButton.Disabled = true;
                IncreaseButton.Disabled = false;
                break;
            default:
                SlotsLabel.Text = slots?.ToString() ?? "0";
                SlotsLabel.FontColorOverride = null;
                DecreaseButton.Disabled = false;
                IncreaseButton.Disabled = false;
                break;
        }
    }

    public bool Matches(string query)
    {
        return string.IsNullOrWhiteSpace(query) ||
               _localizedName.Contains(query, StringComparison.CurrentCultureIgnoreCase) ||
               Job.Id.Contains(query, StringComparison.OrdinalIgnoreCase);
    }
}
