using Content.Client.UserInterface.Controls;
using Content.Pirate.Shared.Silicons.Borgs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.Silicons.Borgs;

[GenerateTypedNameReferences]
public sealed partial class BorgModuleLightingWindow : FancyWindow
{
    public event Action<Color, bool, float>? OnUpdate;

    private static readonly (string Name, float Rate)[] Speeds =
    [
        ("Slow", 0.03f),
        ("Normal", 0.1f),
        ("Fast", 0.3f),
    ];

    private Button[] _speedButtons = default!;
    private float _currentRate = 0.1f;

    public BorgModuleLightingWindow()
    {
        RobustXamlLoader.Load(this);

        _speedButtons = [SpeedSlow, SpeedNormal, SpeedFast];

        SpeedSlow.OnPressed += _ => SelectSpeed(0);
        SpeedNormal.OnPressed += _ => SelectSpeed(1);
        SpeedFast.OnPressed += _ => SelectSpeed(2);

        SelectSpeed(1);
        ConfirmationButton.OnPressed += _ => Update();
    }

    public void UpdateState(BorgModuleLightingBoundUserInterfaceState state)
    {
        ColorSelector.Color = state.LightColor;
        DiscoCheckbox.Pressed = state.DiscoMode;

        _currentRate = state.CycleRate;
        for (var i = 0; i < Speeds.Length; i++)
        {
            if (MathF.Abs(Speeds[i].Rate - state.CycleRate) < 0.001f)
            {
                SelectSpeed(i);
                return;
            }
        }
    }

    private void SelectSpeed(int index)
    {
        for (var i = 0; i < _speedButtons.Length; i++)
            _speedButtons[i].Pressed = i == index;

        _currentRate = Speeds[index].Rate;
    }

    private void Update()
    {
        OnUpdate?.Invoke(ColorSelector.Color, DiscoCheckbox.Pressed, _currentRate);
    }
}
