using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client._DV.Abilities.Psionics;

[GenerateTypedNameReferences]
public sealed partial class EruptionWarning : DefaultWindow
{
    public EruptionWarning()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Close();
    }
}
