using Content.Client.UserInterface.Controls;
using Content.Shared._Pirate.Reputation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.Reputation.UI;

[GenerateTypedNameReferences]
public sealed partial class ContractsWindow : FancyWindow
{
    public event Action<int>? OnAccept;
    public event Action<int>? OnComplete;
    public event Action<int>? OnReject;

    public ContractsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ContractsState state)
    {
        Level.Text = state.Level is {} level ? Loc.GetString(level) : string.Empty;
        Reputation.Text = Loc.GetString("contracts-reputation", ("reputation", state.Reputation));

        Contracts.RemoveAllChildren();
        var slotsFull = true;
        for (int i = 0; i < state.ContractSlots.Count; i++)
        {
            var index = i;
            if (state.ContractSlots[i].ObjectiveTitle is {} title)
            {
                var contract = new Contract(title, state.ContractSlots[i].Icon);
                contract.OnComplete += () => OnComplete?.Invoke(index);
                Contracts.AddChild(contract);
                // TODO: green when objective is complete
            }
            else
            {
                var empty = new EmptyContract(state.ContractSlots[i].NextUnlock);
                empty.OnUnlock += EnableAccepts;
                if (!empty.IsLocked)
                    slotsFull = false;
                Contracts.AddChild(empty);
            }
        }

        Offerings.RemoveAllChildren();
        for (int i = 0; i < state.OfferingSlots.Count; i++)
        {
            var index = i;
            var offering = new ContractOffering(state.OfferingSlots[i]);
            offering.AcceptDisabled = slotsFull;
            offering.OnAccept += () => OnAccept?.Invoke(index);
            offering.OnReject += () => OnReject?.Invoke(index);
            Offerings.AddChild(offering);
        }
    }

    private void EnableAccepts()
    {
        foreach (var child in Offerings.Children)
        {
            ((ContractOffering) child).AcceptDisabled = false;
        }
    }
}
