using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.Reputation.UI;

/// <summary>
/// Contract control placed in a slot that has a contract active.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class Contract : BoxContainer
{
    public event Action? OnComplete;

    public Contract(string title, SpriteSpecifier? icon)
    {
        RobustXamlLoader.Load(this);

        Title.Text = title;
        if (icon is {} sprite)
            Icon.SetFromSpriteSpecifier(sprite);
        else
            Icon.Visible = false;

        CompleteButton.OnPressed += _ => OnComplete?.Invoke();
    }
}
