// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.Voting.UI;

[GenerateTypedNameReferences]
public sealed partial class PirateVoteOption : BoxContainer
{
    public PirateVoteOption()
    {
        RobustXamlLoader.Load(this);
    }
}
