// SPDX-FileCopyrightText: 2026 Corvax Team Contributors
// SPDX-FileCopyrightText: 2026 CyberLanos <cyber.lanos00@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using System.IO;
using System.Numerics;

namespace Content.Client._Pirate.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoCardWindow : BaseWindow
{
    public PhotoCardWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var resourceCache = IoCManager.Resolve<IResourceCache>();
        // Pirate: photo card style classes only ever existed in the obsolete StyleNano/StyleSpace
        // sheets, which are no longer the active stylesheet; set the card look directly instead.
        FramePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#FFFFFF"),
            BorderColor = Color.FromHex("#C0C0C0"),
            BorderThickness = new Thickness(4),
        };
        PhotoNameLabel.FontOverride = resourceCache.NotoStack(variation: "Bold", size: 12);
        PhotoNameLabel.FontColorOverride = Color.FromHex("#111111");
        CaptionLabel.ModulateSelfOverride = Color.FromHex("#111111");

        CloseButton.OnPressed += _ => Close();
    }

    public void ShowImage(byte[] imageData)
    {
        try
        {
            using var stream = new MemoryStream(imageData);
            ImageDisplay.Texture = Texture.LoadFromPNGStream(stream);
        }
        catch (Exception ex)
        {
            Logger.WarningS("photo-card",
                $"Failed to load photo card image in {nameof(PhotoCardWindow)}. " +
                $"Message: {ex.Message}\nStackTrace: {ex.StackTrace}");
            ImageDisplay.Texture = null;
        }
    }

    public void ClearImage()
    {
        ImageDisplay.Texture = null;
    }

    public void SetMetadata(string? customName, string? caption)
    {
        PhotoNameLabel.Text = customName ?? string.Empty;
        CaptionLabel.SetMessage(FormattedMessage.FromUnformatted(caption ?? string.Empty));
    }

    protected override DragMode GetDragModeFor(Vector2 _) => DragMode.Move;
}


