// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.UserInterface.Controls; // Pirate: slime morph - DialogWindow name prompt
using Content.Shared._Pirate.SlimeMorph;
using Content.Shared.Administration; // Pirate: slime morph - QuickDialogEntry
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using static Content.Client.Stylesheets.StylesheetHelpers;

namespace Content.Client._Pirate.SlimeMorph;

[GenerateTypedNameReferences]
public sealed partial class SlimeMorphWindow : DefaultWindow
{
    public Action<(MarkingCategories category, int slot, string id)>? OnMarkingSelected;
    public Action<(MarkingCategories category, int slot, Marking marking)>? OnMarkingColorChanged;
    public Action<MarkingCategories>? OnMarkingSlotAdded;
    public Action<(MarkingCategories category, int slot)>? OnMarkingSlotRemoved;

    public Action<Color>? OnSkinColorChanged;
    public Action<Color>? OnEyeColorChanged;
    public Action<Sex>? OnSexChanged;
    public Action<Gender>? OnGenderChanged;
    public Action<float>? OnHeightChanged;
    public Action<float>? OnWidthChanged;

    public Action<NetEntity?>? OnSelectTarget;
    public Action? OnMimic;
    public Action<NetEntity>? OnForget;
    public Action? OnRevert;
    public Action? OnApply;
    public Action? OnReset;

    // Pirate: slime morph v1.1
    public Action<string?>? OnXenotypeChanged;
    public Action? OnAdaptColors;
    public Action<string>? OnSaveAppearance;
    public Action<(string name, string species)>? OnSelectSaved;
    public Action<(string name, string species)>? OnDeleteSaved;
    public Action? OnImport;
    public Action? OnExport;

    private static readonly Color FontDefault = Color.FromHex("#E6E8EE");
    private static readonly Color FontDanger = Color.FromHex("#EDA393");

    private const string BtnClass = "SlimeMorphBtn";
    private const string BtnDangerClass = "SlimeMorphBtnDanger";
    private const string OptionItemClass = "SlimeMorphOption";
    private static bool _stylesInstalled;

    private readonly IEntityManager _entManager;
    private readonly HumanoidAppearanceSystem _humanoidSystem;
    private readonly MarkingManager _markingManager;

    private readonly List<MarkingSection> _sections = new();
    private bool _updating;
    private NetEntity? _selected;
    private EntityUid? _preview;
    private SlimeMorphUiState? _state;

    // Pirate: slime morph v1.1 - the right-side list mixes studied targets (NetEntity) and saved looks
    // (name + xenotype); track which kind is selected so Forget deletes the right one.
    private (string name, string species)? _selectedSaved;
    // Name of the currently-loaded memory (studied/saved/imported), used to prefill the Save dialog.
    private string? _selectedName;
    private readonly List<string?> _xenotypeIds = new();

    private sealed record StudiedKey(NetEntity Target);
    private sealed record SavedKey(string Name, string Species);

    // Pirate: slime morph v1.1 - one collapsible group per marking category (there are ~24, so the
    // list is unusable fully expanded). Header toggles the picker's visibility; empty groups hide.
    private sealed class MarkingSection
    {
        public SingleMarkingPicker Picker = default!;
        public ContainerButton Header = default!;
        public Label ExpandIcon = default!;
        public PanelContainer Dot = default!;
        public BoxContainer Root = default!;
        public bool Collapsed = true;
    }

    public SlimeMorphWindow()
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();
        _markingManager = IoCManager.Resolve<MarkingManager>();
        _humanoidSystem = _entManager.System<HumanoidAppearanceSystem>();

        foreach (var category in SlimeMorphCategories.Editable)
        {
            var picker = new SingleMarkingPicker { Category = category };
            picker.OnMarkingSelect += args =>
            {
                OnMarkingSelected?.Invoke((category, args.slot, args.id));
                PreviewMarkingSelect(category, args.slot, args.id);
            };
            picker.OnColorChanged += args =>
            {
                OnMarkingColorChanged?.Invoke((category, args.slot, args.marking));
                PreviewMarkingColor(category, args.slot, args.marking);
            };
            picker.OnSlotAdd += () => OnMarkingSlotAdded?.Invoke(category);
            picker.OnSlotRemove += slot => OnMarkingSlotRemoved?.Invoke((category, slot));

            if (FindColorContainer(picker) is { } colorBox)
            {
                colorBox.Orientation = BoxContainer.LayoutOrientation.Vertical;
                colorBox.SeparationOverride = 4;
            }

            // The picker draws its own category label; hide it and use a collapsible header instead
            // (icon + name row, styled like the traits kit's category headers).
            if (FindControlByName(picker, "CategoryName") is { } label)
                label.Visible = false;

            var expandIcon = new Label { Text = "▶", Margin = new Thickness(0, 0, 8, 0) };
            var nameLabel = new Label { Text = Loc.GetString($"markings-category-{category}") };
            // A small dot on the right of the header marks categories that currently have a marking.
            var dot = new PanelContainer
            {
                MinSize = new Vector2(8, 8),
                VerticalAlignment = VAlignment.Center,
                Visible = false,
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#6F9FE0") },
            };
            var headerContent = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(8, 5),
                HorizontalExpand = true,
            };
            headerContent.AddChild(expandIcon);
            headerContent.AddChild(nameLabel);
            headerContent.AddChild(new Control { HorizontalExpand = true });
            headerContent.AddChild(dot);

            var header = new ContainerButton { HorizontalExpand = true };
            header.AddChild(headerContent);

            var section = new MarkingSection { Picker = picker, Header = header, ExpandIcon = expandIcon, Dot = dot };
            header.OnPressed += _ =>
            {
                section.Collapsed = !section.Collapsed;
                ApplyCollapse(section);
            };

            var root = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(0, 0, 0, 4) };
            root.AddChild(header);
            root.AddChild(picker);
            section.Root = root;

            MarkingPickers.AddChild(root);
            _sections.Add(section);
        }

        SkinColorSelector.OnColorChanged += color =>
        {
            if (_updating)
                return;
            OnSkinColorChanged?.Invoke(color);
            PreviewField(s => s.SkinColor = color);
        };
        EyeColorSelector.OnColorChanged += color =>
        {
            if (_updating)
                return;
            OnEyeColorChanged?.Invoke(color);
            PreviewField(s => s.EyeColor = color);
        };

        InstallStyles();
        SexButton.OptionStyleClasses.Add(OptionItemClass);
        GenderButton.OptionStyleClasses.Add(OptionItemClass);
        XenotypeButton.OptionStyleClasses.Add(OptionItemClass); // Pirate: slime morph
        XenotypeButton.OnItemSelected += args =>
        {
            XenotypeButton.SelectId(args.Id);
            if (_updating)
                return;
            OnXenotypeChanged?.Invoke(args.Id >= 0 && args.Id < _xenotypeIds.Count ? _xenotypeIds[args.Id] : null);
        };

        foreach (var sex in Enum.GetValues<Sex>())
            SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int) sex);
        SexButton.OnItemSelected += args =>
        {
            SexButton.SelectId(args.Id);
            if (_updating)
                return;
            OnSexChanged?.Invoke((Sex) args.Id);
            PreviewField(s => s.Sex = (Sex) args.Id);
        };

        foreach (var gender in Enum.GetValues<Gender>())
            GenderButton.AddItem(Loc.GetString($"slime-morph-gender-{gender.ToString().ToLower()}"), (int) gender);
        GenderButton.OnItemSelected += args =>
        {
            GenderButton.SelectId(args.Id);
            if (_updating)
                return;
            OnGenderChanged?.Invoke((Gender) args.Id);
            PreviewField(s => s.Gender = (Gender) args.Id);
        };

        HeightSlider.OnValueChanged += _ =>
        {
            HeightValue.Text = HeightSlider.Value.ToString("0.00");
            if (_updating)
                return;
            OnHeightChanged?.Invoke(HeightSlider.Value);
            PreviewField(s => s.Height = HeightSlider.Value);
        };
        WidthSlider.OnValueChanged += _ =>
        {
            WidthValue.Text = WidthSlider.Value.ToString("0.00");
            if (_updating)
                return;
            OnWidthChanged?.Invoke(WidthSlider.Value);
            PreviewField(s => s.Width = WidthSlider.Value);
        };

        RememberedList.OnItemSelected += _ => OnListSelectionChanged();
        RememberedList.OnItemDeselected += _ => OnListSelectionChanged();

        // Pirate: slime morph - one commit button. It mimics a loaded target, otherwise applies the
        // self-edit; both spend nutrition + squish server-side, so a separate "Apply" was redundant.
        MimicButton.OnPressed += _ =>
        {
            if (_state?.CanMimic == true)
                OnMimic?.Invoke();
            else
                OnApply?.Invoke();
        };
        ForgetButton.OnPressed += _ =>
        {
            // Pirate: slime morph - same button forgets a studied target or deletes a saved look.
            if (_selectedSaved is { } saved)
                OnDeleteSaved?.Invoke(saved);
            else if (_selected is { } target)
                OnForget?.Invoke(target);
        };
        RevertButton.OnPressed += _ => OnRevert?.Invoke();
        ResetButton.OnPressed += _ => OnReset?.Invoke();

        // Pirate: slime morph v1.1
        AdaptColorsButton.OnPressed += _ => OnAdaptColors?.Invoke();
        SaveButton.OnPressed += _ => PromptSaveName();
        ImportButton.OnPressed += _ => OnImport?.Invoke();
        ExportButton.OnPressed += _ => OnExport?.Invoke();

        RestyleButtons();
    }

    /// <summary>Show/hide a section's picker per its collapse state and refresh the header caret.</summary>
    private static void ApplyCollapse(MarkingSection section)
    {
        section.Picker.Visible = !section.Collapsed;
        section.ExpandIcon.Text = section.Collapsed ? "▶" : "▼";
    }

    private static Control? FindControlByName(Control control, string name)
    {
        foreach (var child in control.Children)
        {
            if (child.Name == name)
                return child;

            if (FindControlByName(child, name) is { } found)
                return found;
        }

        return null;
    }

    private static BoxContainer? FindColorContainer(Control control)
    {
        foreach (var child in control.Children)
        {
            if (child is BoxContainer { Name: "ColorSelectorContainer" } box)
                return box;

            if (FindColorContainer(child) is { } found)
                return found;
        }

        return null;
    }

    private void OnListSelectionChanged()
    {
        if (_updating)
            return;

        // Pirate: slime morph - the list mixes studied targets and saved looks.
        switch (RememberedList.GetSelected().FirstOrDefault()?.Metadata)
        {
            case StudiedKey studied:
                _selected = studied.Target;
                _selectedSaved = null;
                _selectedName = _state?.Remembered.FirstOrDefault(a => a.Target == studied.Target)?.Name;
                ForgetButton.Disabled = false;
                OnSelectTarget?.Invoke(studied.Target);
                break;
            case SavedKey saved:
                _selected = null;
                _selectedSaved = (saved.Name, saved.Species);
                _selectedName = saved.Name;
                ForgetButton.Disabled = false;
                OnSelectSaved?.Invoke((saved.Name, saved.Species));
                break;
            default:
                _selected = null;
                _selectedSaved = null;
                _selectedName = null;
                ForgetButton.Disabled = true;
                OnSelectTarget?.Invoke(null);
                break;
        }
    }

    public void UpdateState(SlimeMorphUiState state)
    {
        _state = state;
        _updating = true;

        SexButton.SelectId((int) state.Sex);
        GenderButton.SelectId((int) state.Gender);
        UpdateXenotypeButton(state); // Pirate: slime morph
        SkinColorSelector.Color = state.SkinColor;
        EyeColorSelector.Color = state.EyeColor;

        HeightSlider.MinValue = state.MinHeight;
        HeightSlider.MaxValue = state.MaxHeight;
        HeightSlider.Value = state.Height;
        HeightValue.Text = state.Height.ToString("0.00");

        WidthSlider.MinValue = state.MinWidth;
        WidthSlider.MaxValue = state.MaxWidth;
        WidthSlider.Value = state.Width;
        WidthValue.Text = state.Width.ToString("0.00");

        // Use the target species while mimicking.
        var pickerSpecies = state.PickerSpecies ?? state.Species;
        foreach (var section in _sections)
        {
            var picker = section.Picker;
            var category = picker.Category;
            var markings = state.MarkingSet.TryGetCategory(category, out var list)
                ? new List<Marking>(list)
                : new List<Marking>();
            var total = state.MarkingSet.PointsLeft(category) + markings.Count;
            // Used to resolve gradient icons.
            picker.GradientContext = state.MarkingSet;
            // Always scoped to the selected xenotype (defaults to the slime's own species).
            picker.IgnoreSpecies = false;
            picker.Sex = state.Sex;
            picker.UpdateData(markings, pickerSpecies, total);

            // UpdateData hides the picker when a category has no markings; fold that into the whole
            // section so empty groups vanish, and otherwise honor the collapse state.
            section.Root.Visible = picker.Visible;
            if (picker.Visible)
                ApplyCollapse(section);

            // Dot on the header marks categories that currently have a marking selected.
            section.Dot.Visible = markings.Count > 0;
        }

        UpdateRemembered(state);

        // Single commit button: enabled whenever there is a staged look to commit (always, while open).
        MimicButton.Disabled = !(state.CanApply || state.CanMimic);

        UpdatePreview(state);
        RestyleButtons();

        _updating = false;
    }

    private void UpdateRemembered(SlimeMorphUiState state)
    {
        // Preserve the saved-look selection across the rebuild: the server tracks the studied target
        // (SelectedTarget) but has no notion of a "selected saved look", so re-select it ourselves,
        // otherwise clicking a saved entry deselects on the very next state push (Forget stays greyed).
        var keepSaved = _selectedSaved;

        RememberedList.Clear();

        foreach (var appearance in state.Remembered)
        {
            var item = RememberedList.AddItem(Loc.GetString("slime-morph-remembered-entry",
                ("name", appearance.Name),
                ("species", _humanoidSystem.GetSpeciesRepresentation(appearance.Species))));
            item.Metadata = new StudiedKey(appearance.Target);
            if (state.SelectedTarget == appearance.Target)
                item.Selected = true;
        }

        // Pirate: slime morph - saved looks share the list, tagged with a star.
        foreach (var appearance in state.Saved)
        {
            var item = RememberedList.AddItem(Loc.GetString("slime-morph-saved-entry",
                ("name", appearance.Name),
                ("species", _humanoidSystem.GetSpeciesRepresentation(appearance.Species))));
            item.Metadata = new SavedKey(appearance.Name, appearance.Species);
            if (keepSaved is { } k && k.name == appearance.Name && k.species == appearance.Species)
                item.Selected = true;
        }

        if (state.SelectedTarget is { } target)
        {
            _selected = target;
            _selectedSaved = null;
        }
        else if (keepSaved is { } k2 && state.Saved.Any(a => a.Name == k2.name && a.Species == k2.species))
        {
            _selected = null;
            _selectedSaved = k2;
        }
        else
        {
            _selected = null;
            _selectedSaved = null;
        }

        ForgetButton.Disabled = _selected == null && _selectedSaved == null;
    }

    /// <summary>Populate the xenotype dropdown from the morph whitelist (defaults to the slime's own species).</summary>
    private void UpdateXenotypeButton(SlimeMorphUiState state)
    {
        XenotypeButton.Clear();
        _xenotypeIds.Clear();

        var effective = state.PickerSpecies ?? state.Species;
        var selectedId = 0;
        var id = 0;
        foreach (var species in state.MorphableSpecies)
        {
            XenotypeButton.AddItem(_humanoidSystem.GetSpeciesRepresentation(species), id);
            _xenotypeIds.Add(species);
            if (species == effective)
                selectedId = id;
            id++;
        }

        XenotypeButton.SelectId(selectedId);
    }

    /// <summary>Remember a name (e.g. an imported file's) to prefill the next Save prompt.</summary>
    public void SetSuggestedName(string? name)
    {
        _selectedName = name;
    }

    /// <summary>Prompt for a name (prefilled from the loaded memory), then store the staged look.</summary>
    private void PromptSaveName()
    {
        var dialog = new DialogWindow(
            Loc.GetString("slime-morph-save-title"),
            new List<QuickDialogEntry>
            {
                new("name", QuickDialogEntryType.ShortText,
                    Loc.GetString("slime-morph-save-prompt"),
                    Loc.GetString("slime-morph-save-placeholder"),
                    _selectedName),
            });

        dialog.OnConfirmed += results =>
        {
            if (results.TryGetValue("name", out var name) && !string.IsNullOrWhiteSpace(name))
                OnSaveAppearance?.Invoke(name.Trim());
        };
    }

    // ---- Live preview ----

    private void PreviewField(Action<SlimeMorphUiState> mutate)
    {
        if (_state == null)
            return;

        mutate(_state);
        UpdatePreview(_state);
    }

    private void PreviewMarkingColor(MarkingCategories category, int slot, Marking marking)
    {
        if (_updating || _state == null
            || !_state.MarkingSet.TryGetCategory(category, out var list)
            || slot < 0 || slot >= list.Count)
            return;

        for (var i = 0; i < list[slot].MarkingColors.Count && i < marking.MarkingColors.Count; i++)
            list[slot].SetColor(i, marking.MarkingColors[i]);

        UpdatePreview(_state);
    }

    private void PreviewMarkingSelect(MarkingCategories category, int slot, string id)
    {
        if (_updating || _state == null
            || !_markingManager.Markings.TryGetValue(id, out var proto)
            || !_state.MarkingSet.TryGetCategory(category, out var list)
            || slot < 0 || slot >= list.Count)
            return;

        var marking = proto.AsMarking();
        for (var i = 0; i < marking.MarkingColors.Count && i < list[slot].MarkingColors.Count; i++)
            marking.SetColor(i, list[slot].MarkingColors[i]);

        _state.MarkingSet.Replace(category, slot, marking);
        UpdatePreview(_state);
    }

    private void UpdatePreview(SlimeMorphUiState state)
    {
        if (_preview is not { } preview || _entManager.Deleted(preview))
        {
            preview = _entManager.Spawn("MobSlimePersonDummy");
            _preview = preview;
            Preview.SetEntity(preview);
        }

        if (!_entManager.TryGetComponent<HumanoidAppearanceComponent>(preview, out var comp)
            || !_entManager.TryGetComponent<SpriteComponent>(preview, out var sprite))
            return;

        comp.MarkingSet = new MarkingSet(state.MarkingSet);
        comp.EyeColor = state.EyeColor;
        comp.Sex = state.Sex;
        comp.Gender = state.Gender;
        comp.Height = state.Height;
        comp.Width = state.Width;

        _humanoidSystem.SetSkinColor(preview, state.SkinColor, false);

        // Mirror the copied structural layers (baked muzzles, digitigrade legs, ...) so the preview
        // matches. Layers not present in state.BodyLayers are cleared back to the slime's own sprite.
        var wanted = state.BodyLayers.ToDictionary(bodyLayer => bodyLayer.Layer);
        foreach (var layer in comp.CustomBaseLayers.Keys.ToList())
        {
            if (layer != HumanoidVisualLayers.Eyes && !wanted.ContainsKey(layer))
                comp.CustomBaseLayers.Remove(layer);
        }

        foreach (var (layer, info) in wanted)
        {
            var f = info.ColorFactor;
            var layerColor = new Color(
                state.SkinColor.R * f,
                state.SkinColor.G * f,
                state.SkinColor.B * f,
                state.CopiedLayerAlpha);
            _humanoidSystem.SetBaseLayerId(preview, layer, info.SpriteId, false);
            _humanoidSystem.SetBaseLayerColor(preview, layer, layerColor, false);
        }

        _humanoidSystem.UpdateSprite((preview, comp, sprite));
    }

    // ---- Button / selector styling ----

    /// <summary>
    /// Tag every button in the window with our style classes so the installed rules (with hover /
    /// pressed states) apply, and add small padding around the color-channel spinboxes.
    /// </summary>
    private void RestyleButtons()
    {
        ClassifyControls(Contents);
        RevertButton.AddStyleClass(BtnDangerClass);

        foreach (var button in new[] { MimicButton, ResetButton, SaveButton, ForgetButton, ImportButton, ExportButton })
            button.Label.FontColorOverride = FontDefault;
        RevertButton.Label.FontColorOverride = FontDanger;
    }

    private void ClassifyControls(Control control)
    {
        foreach (var child in control.Children)
        {
            switch (child)
            {
                case ContainerButton button when !button.HasStyleClass(BtnClass):
                    button.AddStyleClass(BtnClass);
                    break;
                // Breathing room: gap before the "-" stepper and padding off the panel edge.
                case SpinBox spin:
                    spin.Margin = new Thickness(6, 0, 4, 0);
                    break;
            }

            ClassifyControls(child);
        }
    }

    /// <summary>
    /// Button/OptionButton dropdown popups live under the modal root, not this window, so a
    /// window-scoped stylesheet can't reach them. Append rules (scoped to our unique classes, with
    /// full hover/pressed/disabled states) to the global sheet once.
    /// </summary>
    private static void InstallStyles()
    {
        if (_stylesInstalled)
            return;

        var ui = IoCManager.Resolve<IUserInterfaceManager>();
        if (ui.Stylesheet is not { } sheet)
            return;

        var rules = new List<Robust.Client.UserInterface.StyleRule>(sheet.Rules);

        // Normal window buttons (raised), with hover/pressed/disabled feedback.
        AddButtonRules(rules, BtnClass,
            MakeBox("#272B35", "#383D4A"),
            MakeBox("#2E323D", "#4A505E"),
            MakeBox("#21242D", "#383D4A"),
            MakeBox("#1E2129", "#2A2E39"));

        // Destructive (Revert).
        AddButtonRules(rules, BtnDangerClass,
            MakeBox("#3A2622", "#6B3A32"),
            MakeBox("#47302B", "#7E463C"),
            MakeBox("#2E211E", "#6B3A32"),
            MakeBox("#241A18", "#3A2622"));

        // Dropdown popup items.
        AddButtonRules(rules, OptionItemClass,
            MakeBox("#21242D", "#2E323D"),
            MakeBox("#272B35", "#383D4A"),
            MakeBox("#24344A", "#6F9FE0"),
            MakeBox("#1E2129", "#2A2E39"));

        ui.Stylesheet = new Robust.Client.UserInterface.Stylesheet(rules);
        _stylesInstalled = true;
    }

    private static void AddButtonRules(List<Robust.Client.UserInterface.StyleRule> rules, string styleClass,
        StyleBoxFlat normal, StyleBoxFlat hover, StyleBoxFlat pressed, StyleBoxFlat disabled)
    {
        rules.Add(E<ContainerButton>().Class(styleClass).Pseudo(ContainerButton.StylePseudoClassNormal)
            .Box(normal).Modulate(Color.White));
        rules.Add(E<ContainerButton>().Class(styleClass).Pseudo(ContainerButton.StylePseudoClassHover)
            .Box(hover).Modulate(Color.White));
        rules.Add(E<ContainerButton>().Class(styleClass).Pseudo(ContainerButton.StylePseudoClassPressed)
            .Box(pressed).Modulate(Color.White));
        rules.Add(E<ContainerButton>().Class(styleClass).Pseudo(ContainerButton.StylePseudoClassDisabled)
            .Box(disabled).Modulate(Color.White));
    }

    private static StyleBoxFlat MakeBox(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 14,
            ContentMarginRightOverride = 14,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
        };
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        if (_preview is { } preview && !_entManager.Deleted(preview))
            _entManager.DeleteEntity(preview);
        _preview = null;
    }
}
